/*
CloudRadial

The CloudRadial API is currently in development. For more information visit <a href='https://radials.io/api' target='_blank'>https://radials.io/api</a>

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloudradial

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the FlexibleAssetTypeAttributesUpdateDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FlexibleAssetTypeAttributesUpdateDto{}

// FlexibleAssetTypeAttributesUpdateDto struct for FlexibleAssetTypeAttributesUpdateDto
type FlexibleAssetTypeAttributesUpdateDto struct {
	Fields      []FlexibleAssetFieldAttributesCreateDto `json:"fields,omitempty"`
	Name        string                                  `json:"name"`
	Description NullableString                          `json:"description,omitempty"`
	Icon        NullableString                          `json:"icon,omitempty"`
	ShowInMenu  *bool                                   `json:"show-in-menu,omitempty"`
}

type _FlexibleAssetTypeAttributesUpdateDto FlexibleAssetTypeAttributesUpdateDto

// NewFlexibleAssetTypeAttributesUpdateDto instantiates a new FlexibleAssetTypeAttributesUpdateDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFlexibleAssetTypeAttributesUpdateDto(name string) *FlexibleAssetTypeAttributesUpdateDto {
	this := FlexibleAssetTypeAttributesUpdateDto{}
	this.Name = name
	return &this
}

// NewFlexibleAssetTypeAttributesUpdateDtoWithDefaults instantiates a new FlexibleAssetTypeAttributesUpdateDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFlexibleAssetTypeAttributesUpdateDtoWithDefaults() *FlexibleAssetTypeAttributesUpdateDto {
	this := FlexibleAssetTypeAttributesUpdateDto{}
	return &this
}

// GetFields returns the Fields field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FlexibleAssetTypeAttributesUpdateDto) GetFields() []FlexibleAssetFieldAttributesCreateDto {
	if o == nil {
		var ret []FlexibleAssetFieldAttributesCreateDto
		return ret
	}
	return o.Fields
}

// GetFieldsOk returns a tuple with the Fields field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FlexibleAssetTypeAttributesUpdateDto) GetFieldsOk() ([]FlexibleAssetFieldAttributesCreateDto, bool) {
	if o == nil || IsNil(o.Fields) {
		return nil, false
	}
	return o.Fields, true
}

// HasFields returns a boolean if a field has been set.
func (o *FlexibleAssetTypeAttributesUpdateDto) HasFields() bool {
	if o != nil && !IsNil(o.Fields) {
		return true
	}

	return false
}

// SetFields gets a reference to the given []FlexibleAssetFieldAttributesCreateDto and assigns it to the Fields field.
func (o *FlexibleAssetTypeAttributesUpdateDto) SetFields(v []FlexibleAssetFieldAttributesCreateDto) {
	o.Fields = v
}

// GetName returns the Name field value
func (o *FlexibleAssetTypeAttributesUpdateDto) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *FlexibleAssetTypeAttributesUpdateDto) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *FlexibleAssetTypeAttributesUpdateDto) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FlexibleAssetTypeAttributesUpdateDto) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FlexibleAssetTypeAttributesUpdateDto) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *FlexibleAssetTypeAttributesUpdateDto) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *FlexibleAssetTypeAttributesUpdateDto) SetDescription(v string) {
	o.Description.Set(&v)
}

// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *FlexibleAssetTypeAttributesUpdateDto) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *FlexibleAssetTypeAttributesUpdateDto) UnsetDescription() {
	o.Description.Unset()
}

// GetIcon returns the Icon field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FlexibleAssetTypeAttributesUpdateDto) GetIcon() string {
	if o == nil || IsNil(o.Icon.Get()) {
		var ret string
		return ret
	}
	return *o.Icon.Get()
}

// GetIconOk returns a tuple with the Icon field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FlexibleAssetTypeAttributesUpdateDto) GetIconOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Icon.Get(), o.Icon.IsSet()
}

// HasIcon returns a boolean if a field has been set.
func (o *FlexibleAssetTypeAttributesUpdateDto) HasIcon() bool {
	if o != nil && o.Icon.IsSet() {
		return true
	}

	return false
}

// SetIcon gets a reference to the given NullableString and assigns it to the Icon field.
func (o *FlexibleAssetTypeAttributesUpdateDto) SetIcon(v string) {
	o.Icon.Set(&v)
}

// SetIconNil sets the value for Icon to be an explicit nil
func (o *FlexibleAssetTypeAttributesUpdateDto) SetIconNil() {
	o.Icon.Set(nil)
}

// UnsetIcon ensures that no value is present for Icon, not even an explicit nil
func (o *FlexibleAssetTypeAttributesUpdateDto) UnsetIcon() {
	o.Icon.Unset()
}

// GetShowInMenu returns the ShowInMenu field value if set, zero value otherwise.
func (o *FlexibleAssetTypeAttributesUpdateDto) GetShowInMenu() bool {
	if o == nil || IsNil(o.ShowInMenu) {
		var ret bool
		return ret
	}
	return *o.ShowInMenu
}

// GetShowInMenuOk returns a tuple with the ShowInMenu field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FlexibleAssetTypeAttributesUpdateDto) GetShowInMenuOk() (*bool, bool) {
	if o == nil || IsNil(o.ShowInMenu) {
		return nil, false
	}
	return o.ShowInMenu, true
}

// HasShowInMenu returns a boolean if a field has been set.
func (o *FlexibleAssetTypeAttributesUpdateDto) HasShowInMenu() bool {
	if o != nil && !IsNil(o.ShowInMenu) {
		return true
	}

	return false
}

// SetShowInMenu gets a reference to the given bool and assigns it to the ShowInMenu field.
func (o *FlexibleAssetTypeAttributesUpdateDto) SetShowInMenu(v bool) {
	o.ShowInMenu = &v
}

func (o FlexibleAssetTypeAttributesUpdateDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FlexibleAssetTypeAttributesUpdateDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Fields != nil {
		toSerialize["fields"] = o.Fields
	}
	toSerialize["name"] = o.Name
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if o.Icon.IsSet() {
		toSerialize["icon"] = o.Icon.Get()
	}
	if !IsNil(o.ShowInMenu) {
		toSerialize["show-in-menu"] = o.ShowInMenu
	}
	return toSerialize, nil
}

func (o *FlexibleAssetTypeAttributesUpdateDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFlexibleAssetTypeAttributesUpdateDto := _FlexibleAssetTypeAttributesUpdateDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFlexibleAssetTypeAttributesUpdateDto)

	if err != nil {
		return err
	}

	*o = FlexibleAssetTypeAttributesUpdateDto(varFlexibleAssetTypeAttributesUpdateDto)

	return err
}

type NullableFlexibleAssetTypeAttributesUpdateDto struct {
	value *FlexibleAssetTypeAttributesUpdateDto
	isSet bool
}

func (v NullableFlexibleAssetTypeAttributesUpdateDto) Get() *FlexibleAssetTypeAttributesUpdateDto {
	return v.value
}

func (v *NullableFlexibleAssetTypeAttributesUpdateDto) Set(val *FlexibleAssetTypeAttributesUpdateDto) {
	v.value = val
	v.isSet = true
}

func (v NullableFlexibleAssetTypeAttributesUpdateDto) IsSet() bool {
	return v.isSet
}

func (v *NullableFlexibleAssetTypeAttributesUpdateDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFlexibleAssetTypeAttributesUpdateDto(val *FlexibleAssetTypeAttributesUpdateDto) *NullableFlexibleAssetTypeAttributesUpdateDto {
	return &NullableFlexibleAssetTypeAttributesUpdateDto{value: val, isSet: true}
}

func (v NullableFlexibleAssetTypeAttributesUpdateDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFlexibleAssetTypeAttributesUpdateDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
