/*
CloudRadial

The CloudRadial API is currently in development. For more information visit <a href='https://radials.io/api' target='_blank'>https://radials.io/api</a>

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloudradial

import (
	"encoding/json"
)

// checks if the CompanyCatalogQuestionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CompanyCatalogQuestionResponse{}

// CompanyCatalogQuestionResponse struct for CompanyCatalogQuestionResponse
type CompanyCatalogQuestionResponse struct {
	CompanyCatalogQuestionId *int32                                        `json:"companyCatalogQuestionId,omitempty"`
	Label                    NullableString                                `json:"label,omitempty"`
	Info                     NullableString                                `json:"info,omitempty"`
	Options                  NullableString                                `json:"options,omitempty"`
	Placeholder              NullableString                                `json:"placeholder,omitempty"`
	Type                     *CatalogQuestionType                          `json:"type,omitempty"`
	IsRequired               *bool                                         `json:"isRequired,omitempty"`
	IsSubject                *bool                                         `json:"isSubject,omitempty"`
	IsDescription            *bool                                         `json:"isDescription,omitempty"`
	Order                    *int32                                        `json:"order,omitempty"`
	DefaultValue             NullableString                                `json:"defaultValue,omitempty"`
	JsonId                   NullableString                                `json:"jsonId,omitempty"`
	IsIncludeInTicket        *bool                                         `json:"isIncludeInTicket,omitempty"`
	IsUserLookup             *bool                                         `json:"isUserLookup,omitempty"`
	CustomFieldName          NullableString                                `json:"customFieldName,omitempty"`
	HideConditions           []CompanyCatalogQuestionHideConditionResponse `json:"hideConditions,omitempty"`
}

// NewCompanyCatalogQuestionResponse instantiates a new CompanyCatalogQuestionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCompanyCatalogQuestionResponse() *CompanyCatalogQuestionResponse {
	this := CompanyCatalogQuestionResponse{}
	return &this
}

// NewCompanyCatalogQuestionResponseWithDefaults instantiates a new CompanyCatalogQuestionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCompanyCatalogQuestionResponseWithDefaults() *CompanyCatalogQuestionResponse {
	this := CompanyCatalogQuestionResponse{}
	return &this
}

// GetCompanyCatalogQuestionId returns the CompanyCatalogQuestionId field value if set, zero value otherwise.
func (o *CompanyCatalogQuestionResponse) GetCompanyCatalogQuestionId() int32 {
	if o == nil || IsNil(o.CompanyCatalogQuestionId) {
		var ret int32
		return ret
	}
	return *o.CompanyCatalogQuestionId
}

// GetCompanyCatalogQuestionIdOk returns a tuple with the CompanyCatalogQuestionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyCatalogQuestionResponse) GetCompanyCatalogQuestionIdOk() (*int32, bool) {
	if o == nil || IsNil(o.CompanyCatalogQuestionId) {
		return nil, false
	}
	return o.CompanyCatalogQuestionId, true
}

// HasCompanyCatalogQuestionId returns a boolean if a field has been set.
func (o *CompanyCatalogQuestionResponse) HasCompanyCatalogQuestionId() bool {
	if o != nil && !IsNil(o.CompanyCatalogQuestionId) {
		return true
	}

	return false
}

// SetCompanyCatalogQuestionId gets a reference to the given int32 and assigns it to the CompanyCatalogQuestionId field.
func (o *CompanyCatalogQuestionResponse) SetCompanyCatalogQuestionId(v int32) {
	o.CompanyCatalogQuestionId = &v
}

// GetLabel returns the Label field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CompanyCatalogQuestionResponse) GetLabel() string {
	if o == nil || IsNil(o.Label.Get()) {
		var ret string
		return ret
	}
	return *o.Label.Get()
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CompanyCatalogQuestionResponse) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Label.Get(), o.Label.IsSet()
}

// HasLabel returns a boolean if a field has been set.
func (o *CompanyCatalogQuestionResponse) HasLabel() bool {
	if o != nil && o.Label.IsSet() {
		return true
	}

	return false
}

// SetLabel gets a reference to the given NullableString and assigns it to the Label field.
func (o *CompanyCatalogQuestionResponse) SetLabel(v string) {
	o.Label.Set(&v)
}

// SetLabelNil sets the value for Label to be an explicit nil
func (o *CompanyCatalogQuestionResponse) SetLabelNil() {
	o.Label.Set(nil)
}

// UnsetLabel ensures that no value is present for Label, not even an explicit nil
func (o *CompanyCatalogQuestionResponse) UnsetLabel() {
	o.Label.Unset()
}

// GetInfo returns the Info field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CompanyCatalogQuestionResponse) GetInfo() string {
	if o == nil || IsNil(o.Info.Get()) {
		var ret string
		return ret
	}
	return *o.Info.Get()
}

// GetInfoOk returns a tuple with the Info field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CompanyCatalogQuestionResponse) GetInfoOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Info.Get(), o.Info.IsSet()
}

// HasInfo returns a boolean if a field has been set.
func (o *CompanyCatalogQuestionResponse) HasInfo() bool {
	if o != nil && o.Info.IsSet() {
		return true
	}

	return false
}

// SetInfo gets a reference to the given NullableString and assigns it to the Info field.
func (o *CompanyCatalogQuestionResponse) SetInfo(v string) {
	o.Info.Set(&v)
}

// SetInfoNil sets the value for Info to be an explicit nil
func (o *CompanyCatalogQuestionResponse) SetInfoNil() {
	o.Info.Set(nil)
}

// UnsetInfo ensures that no value is present for Info, not even an explicit nil
func (o *CompanyCatalogQuestionResponse) UnsetInfo() {
	o.Info.Unset()
}

// GetOptions returns the Options field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CompanyCatalogQuestionResponse) GetOptions() string {
	if o == nil || IsNil(o.Options.Get()) {
		var ret string
		return ret
	}
	return *o.Options.Get()
}

// GetOptionsOk returns a tuple with the Options field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CompanyCatalogQuestionResponse) GetOptionsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Options.Get(), o.Options.IsSet()
}

// HasOptions returns a boolean if a field has been set.
func (o *CompanyCatalogQuestionResponse) HasOptions() bool {
	if o != nil && o.Options.IsSet() {
		return true
	}

	return false
}

// SetOptions gets a reference to the given NullableString and assigns it to the Options field.
func (o *CompanyCatalogQuestionResponse) SetOptions(v string) {
	o.Options.Set(&v)
}

// SetOptionsNil sets the value for Options to be an explicit nil
func (o *CompanyCatalogQuestionResponse) SetOptionsNil() {
	o.Options.Set(nil)
}

// UnsetOptions ensures that no value is present for Options, not even an explicit nil
func (o *CompanyCatalogQuestionResponse) UnsetOptions() {
	o.Options.Unset()
}

// GetPlaceholder returns the Placeholder field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CompanyCatalogQuestionResponse) GetPlaceholder() string {
	if o == nil || IsNil(o.Placeholder.Get()) {
		var ret string
		return ret
	}
	return *o.Placeholder.Get()
}

// GetPlaceholderOk returns a tuple with the Placeholder field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CompanyCatalogQuestionResponse) GetPlaceholderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Placeholder.Get(), o.Placeholder.IsSet()
}

// HasPlaceholder returns a boolean if a field has been set.
func (o *CompanyCatalogQuestionResponse) HasPlaceholder() bool {
	if o != nil && o.Placeholder.IsSet() {
		return true
	}

	return false
}

// SetPlaceholder gets a reference to the given NullableString and assigns it to the Placeholder field.
func (o *CompanyCatalogQuestionResponse) SetPlaceholder(v string) {
	o.Placeholder.Set(&v)
}

// SetPlaceholderNil sets the value for Placeholder to be an explicit nil
func (o *CompanyCatalogQuestionResponse) SetPlaceholderNil() {
	o.Placeholder.Set(nil)
}

// UnsetPlaceholder ensures that no value is present for Placeholder, not even an explicit nil
func (o *CompanyCatalogQuestionResponse) UnsetPlaceholder() {
	o.Placeholder.Unset()
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *CompanyCatalogQuestionResponse) GetType() CatalogQuestionType {
	if o == nil || IsNil(o.Type) {
		var ret CatalogQuestionType
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyCatalogQuestionResponse) GetTypeOk() (*CatalogQuestionType, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *CompanyCatalogQuestionResponse) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given CatalogQuestionType and assigns it to the Type field.
func (o *CompanyCatalogQuestionResponse) SetType(v CatalogQuestionType) {
	o.Type = &v
}

// GetIsRequired returns the IsRequired field value if set, zero value otherwise.
func (o *CompanyCatalogQuestionResponse) GetIsRequired() bool {
	if o == nil || IsNil(o.IsRequired) {
		var ret bool
		return ret
	}
	return *o.IsRequired
}

// GetIsRequiredOk returns a tuple with the IsRequired field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyCatalogQuestionResponse) GetIsRequiredOk() (*bool, bool) {
	if o == nil || IsNil(o.IsRequired) {
		return nil, false
	}
	return o.IsRequired, true
}

// HasIsRequired returns a boolean if a field has been set.
func (o *CompanyCatalogQuestionResponse) HasIsRequired() bool {
	if o != nil && !IsNil(o.IsRequired) {
		return true
	}

	return false
}

// SetIsRequired gets a reference to the given bool and assigns it to the IsRequired field.
func (o *CompanyCatalogQuestionResponse) SetIsRequired(v bool) {
	o.IsRequired = &v
}

// GetIsSubject returns the IsSubject field value if set, zero value otherwise.
func (o *CompanyCatalogQuestionResponse) GetIsSubject() bool {
	if o == nil || IsNil(o.IsSubject) {
		var ret bool
		return ret
	}
	return *o.IsSubject
}

// GetIsSubjectOk returns a tuple with the IsSubject field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyCatalogQuestionResponse) GetIsSubjectOk() (*bool, bool) {
	if o == nil || IsNil(o.IsSubject) {
		return nil, false
	}
	return o.IsSubject, true
}

// HasIsSubject returns a boolean if a field has been set.
func (o *CompanyCatalogQuestionResponse) HasIsSubject() bool {
	if o != nil && !IsNil(o.IsSubject) {
		return true
	}

	return false
}

// SetIsSubject gets a reference to the given bool and assigns it to the IsSubject field.
func (o *CompanyCatalogQuestionResponse) SetIsSubject(v bool) {
	o.IsSubject = &v
}

// GetIsDescription returns the IsDescription field value if set, zero value otherwise.
func (o *CompanyCatalogQuestionResponse) GetIsDescription() bool {
	if o == nil || IsNil(o.IsDescription) {
		var ret bool
		return ret
	}
	return *o.IsDescription
}

// GetIsDescriptionOk returns a tuple with the IsDescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyCatalogQuestionResponse) GetIsDescriptionOk() (*bool, bool) {
	if o == nil || IsNil(o.IsDescription) {
		return nil, false
	}
	return o.IsDescription, true
}

// HasIsDescription returns a boolean if a field has been set.
func (o *CompanyCatalogQuestionResponse) HasIsDescription() bool {
	if o != nil && !IsNil(o.IsDescription) {
		return true
	}

	return false
}

// SetIsDescription gets a reference to the given bool and assigns it to the IsDescription field.
func (o *CompanyCatalogQuestionResponse) SetIsDescription(v bool) {
	o.IsDescription = &v
}

// GetOrder returns the Order field value if set, zero value otherwise.
func (o *CompanyCatalogQuestionResponse) GetOrder() int32 {
	if o == nil || IsNil(o.Order) {
		var ret int32
		return ret
	}
	return *o.Order
}

// GetOrderOk returns a tuple with the Order field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyCatalogQuestionResponse) GetOrderOk() (*int32, bool) {
	if o == nil || IsNil(o.Order) {
		return nil, false
	}
	return o.Order, true
}

// HasOrder returns a boolean if a field has been set.
func (o *CompanyCatalogQuestionResponse) HasOrder() bool {
	if o != nil && !IsNil(o.Order) {
		return true
	}

	return false
}

// SetOrder gets a reference to the given int32 and assigns it to the Order field.
func (o *CompanyCatalogQuestionResponse) SetOrder(v int32) {
	o.Order = &v
}

// GetDefaultValue returns the DefaultValue field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CompanyCatalogQuestionResponse) GetDefaultValue() string {
	if o == nil || IsNil(o.DefaultValue.Get()) {
		var ret string
		return ret
	}
	return *o.DefaultValue.Get()
}

// GetDefaultValueOk returns a tuple with the DefaultValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CompanyCatalogQuestionResponse) GetDefaultValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DefaultValue.Get(), o.DefaultValue.IsSet()
}

// HasDefaultValue returns a boolean if a field has been set.
func (o *CompanyCatalogQuestionResponse) HasDefaultValue() bool {
	if o != nil && o.DefaultValue.IsSet() {
		return true
	}

	return false
}

// SetDefaultValue gets a reference to the given NullableString and assigns it to the DefaultValue field.
func (o *CompanyCatalogQuestionResponse) SetDefaultValue(v string) {
	o.DefaultValue.Set(&v)
}

// SetDefaultValueNil sets the value for DefaultValue to be an explicit nil
func (o *CompanyCatalogQuestionResponse) SetDefaultValueNil() {
	o.DefaultValue.Set(nil)
}

// UnsetDefaultValue ensures that no value is present for DefaultValue, not even an explicit nil
func (o *CompanyCatalogQuestionResponse) UnsetDefaultValue() {
	o.DefaultValue.Unset()
}

// GetJsonId returns the JsonId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CompanyCatalogQuestionResponse) GetJsonId() string {
	if o == nil || IsNil(o.JsonId.Get()) {
		var ret string
		return ret
	}
	return *o.JsonId.Get()
}

// GetJsonIdOk returns a tuple with the JsonId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CompanyCatalogQuestionResponse) GetJsonIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.JsonId.Get(), o.JsonId.IsSet()
}

// HasJsonId returns a boolean if a field has been set.
func (o *CompanyCatalogQuestionResponse) HasJsonId() bool {
	if o != nil && o.JsonId.IsSet() {
		return true
	}

	return false
}

// SetJsonId gets a reference to the given NullableString and assigns it to the JsonId field.
func (o *CompanyCatalogQuestionResponse) SetJsonId(v string) {
	o.JsonId.Set(&v)
}

// SetJsonIdNil sets the value for JsonId to be an explicit nil
func (o *CompanyCatalogQuestionResponse) SetJsonIdNil() {
	o.JsonId.Set(nil)
}

// UnsetJsonId ensures that no value is present for JsonId, not even an explicit nil
func (o *CompanyCatalogQuestionResponse) UnsetJsonId() {
	o.JsonId.Unset()
}

// GetIsIncludeInTicket returns the IsIncludeInTicket field value if set, zero value otherwise.
func (o *CompanyCatalogQuestionResponse) GetIsIncludeInTicket() bool {
	if o == nil || IsNil(o.IsIncludeInTicket) {
		var ret bool
		return ret
	}
	return *o.IsIncludeInTicket
}

// GetIsIncludeInTicketOk returns a tuple with the IsIncludeInTicket field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyCatalogQuestionResponse) GetIsIncludeInTicketOk() (*bool, bool) {
	if o == nil || IsNil(o.IsIncludeInTicket) {
		return nil, false
	}
	return o.IsIncludeInTicket, true
}

// HasIsIncludeInTicket returns a boolean if a field has been set.
func (o *CompanyCatalogQuestionResponse) HasIsIncludeInTicket() bool {
	if o != nil && !IsNil(o.IsIncludeInTicket) {
		return true
	}

	return false
}

// SetIsIncludeInTicket gets a reference to the given bool and assigns it to the IsIncludeInTicket field.
func (o *CompanyCatalogQuestionResponse) SetIsIncludeInTicket(v bool) {
	o.IsIncludeInTicket = &v
}

// GetIsUserLookup returns the IsUserLookup field value if set, zero value otherwise.
func (o *CompanyCatalogQuestionResponse) GetIsUserLookup() bool {
	if o == nil || IsNil(o.IsUserLookup) {
		var ret bool
		return ret
	}
	return *o.IsUserLookup
}

// GetIsUserLookupOk returns a tuple with the IsUserLookup field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyCatalogQuestionResponse) GetIsUserLookupOk() (*bool, bool) {
	if o == nil || IsNil(o.IsUserLookup) {
		return nil, false
	}
	return o.IsUserLookup, true
}

// HasIsUserLookup returns a boolean if a field has been set.
func (o *CompanyCatalogQuestionResponse) HasIsUserLookup() bool {
	if o != nil && !IsNil(o.IsUserLookup) {
		return true
	}

	return false
}

// SetIsUserLookup gets a reference to the given bool and assigns it to the IsUserLookup field.
func (o *CompanyCatalogQuestionResponse) SetIsUserLookup(v bool) {
	o.IsUserLookup = &v
}

// GetCustomFieldName returns the CustomFieldName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CompanyCatalogQuestionResponse) GetCustomFieldName() string {
	if o == nil || IsNil(o.CustomFieldName.Get()) {
		var ret string
		return ret
	}
	return *o.CustomFieldName.Get()
}

// GetCustomFieldNameOk returns a tuple with the CustomFieldName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CompanyCatalogQuestionResponse) GetCustomFieldNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CustomFieldName.Get(), o.CustomFieldName.IsSet()
}

// HasCustomFieldName returns a boolean if a field has been set.
func (o *CompanyCatalogQuestionResponse) HasCustomFieldName() bool {
	if o != nil && o.CustomFieldName.IsSet() {
		return true
	}

	return false
}

// SetCustomFieldName gets a reference to the given NullableString and assigns it to the CustomFieldName field.
func (o *CompanyCatalogQuestionResponse) SetCustomFieldName(v string) {
	o.CustomFieldName.Set(&v)
}

// SetCustomFieldNameNil sets the value for CustomFieldName to be an explicit nil
func (o *CompanyCatalogQuestionResponse) SetCustomFieldNameNil() {
	o.CustomFieldName.Set(nil)
}

// UnsetCustomFieldName ensures that no value is present for CustomFieldName, not even an explicit nil
func (o *CompanyCatalogQuestionResponse) UnsetCustomFieldName() {
	o.CustomFieldName.Unset()
}

// GetHideConditions returns the HideConditions field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CompanyCatalogQuestionResponse) GetHideConditions() []CompanyCatalogQuestionHideConditionResponse {
	if o == nil {
		var ret []CompanyCatalogQuestionHideConditionResponse
		return ret
	}
	return o.HideConditions
}

// GetHideConditionsOk returns a tuple with the HideConditions field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CompanyCatalogQuestionResponse) GetHideConditionsOk() ([]CompanyCatalogQuestionHideConditionResponse, bool) {
	if o == nil || IsNil(o.HideConditions) {
		return nil, false
	}
	return o.HideConditions, true
}

// HasHideConditions returns a boolean if a field has been set.
func (o *CompanyCatalogQuestionResponse) HasHideConditions() bool {
	if o != nil && !IsNil(o.HideConditions) {
		return true
	}

	return false
}

// SetHideConditions gets a reference to the given []CompanyCatalogQuestionHideConditionResponse and assigns it to the HideConditions field.
func (o *CompanyCatalogQuestionResponse) SetHideConditions(v []CompanyCatalogQuestionHideConditionResponse) {
	o.HideConditions = v
}

func (o CompanyCatalogQuestionResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CompanyCatalogQuestionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CompanyCatalogQuestionId) {
		toSerialize["companyCatalogQuestionId"] = o.CompanyCatalogQuestionId
	}
	if o.Label.IsSet() {
		toSerialize["label"] = o.Label.Get()
	}
	if o.Info.IsSet() {
		toSerialize["info"] = o.Info.Get()
	}
	if o.Options.IsSet() {
		toSerialize["options"] = o.Options.Get()
	}
	if o.Placeholder.IsSet() {
		toSerialize["placeholder"] = o.Placeholder.Get()
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.IsRequired) {
		toSerialize["isRequired"] = o.IsRequired
	}
	if !IsNil(o.IsSubject) {
		toSerialize["isSubject"] = o.IsSubject
	}
	if !IsNil(o.IsDescription) {
		toSerialize["isDescription"] = o.IsDescription
	}
	if !IsNil(o.Order) {
		toSerialize["order"] = o.Order
	}
	if o.DefaultValue.IsSet() {
		toSerialize["defaultValue"] = o.DefaultValue.Get()
	}
	if o.JsonId.IsSet() {
		toSerialize["jsonId"] = o.JsonId.Get()
	}
	if !IsNil(o.IsIncludeInTicket) {
		toSerialize["isIncludeInTicket"] = o.IsIncludeInTicket
	}
	if !IsNil(o.IsUserLookup) {
		toSerialize["isUserLookup"] = o.IsUserLookup
	}
	if o.CustomFieldName.IsSet() {
		toSerialize["customFieldName"] = o.CustomFieldName.Get()
	}
	if o.HideConditions != nil {
		toSerialize["hideConditions"] = o.HideConditions
	}
	return toSerialize, nil
}

type NullableCompanyCatalogQuestionResponse struct {
	value *CompanyCatalogQuestionResponse
	isSet bool
}

func (v NullableCompanyCatalogQuestionResponse) Get() *CompanyCatalogQuestionResponse {
	return v.value
}

func (v *NullableCompanyCatalogQuestionResponse) Set(val *CompanyCatalogQuestionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCompanyCatalogQuestionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCompanyCatalogQuestionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCompanyCatalogQuestionResponse(val *CompanyCatalogQuestionResponse) *NullableCompanyCatalogQuestionResponse {
	return &NullableCompanyCatalogQuestionResponse{value: val, isSet: true}
}

func (v NullableCompanyCatalogQuestionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCompanyCatalogQuestionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
