/*
CloudRadial

The CloudRadial API is currently in development. For more information visit <a href='https://radials.io/api' target='_blank'>https://radials.io/api</a>

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncentral

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the FlexibleAssetFieldCreateDtoFlexibleAssetRequestDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FlexibleAssetFieldCreateDtoFlexibleAssetRequestDto{}

// FlexibleAssetFieldCreateDtoFlexibleAssetRequestDto struct for FlexibleAssetFieldCreateDtoFlexibleAssetRequestDto
type FlexibleAssetFieldCreateDtoFlexibleAssetRequestDto struct {
	Data FlexibleAssetFieldCreateDto `json:"data"`
}

type _FlexibleAssetFieldCreateDtoFlexibleAssetRequestDto FlexibleAssetFieldCreateDtoFlexibleAssetRequestDto

// NewFlexibleAssetFieldCreateDtoFlexibleAssetRequestDto instantiates a new FlexibleAssetFieldCreateDtoFlexibleAssetRequestDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFlexibleAssetFieldCreateDtoFlexibleAssetRequestDto(data FlexibleAssetFieldCreateDto) *FlexibleAssetFieldCreateDtoFlexibleAssetRequestDto {
	this := FlexibleAssetFieldCreateDtoFlexibleAssetRequestDto{}
	this.Data = data
	return &this
}

// NewFlexibleAssetFieldCreateDtoFlexibleAssetRequestDtoWithDefaults instantiates a new FlexibleAssetFieldCreateDtoFlexibleAssetRequestDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFlexibleAssetFieldCreateDtoFlexibleAssetRequestDtoWithDefaults() *FlexibleAssetFieldCreateDtoFlexibleAssetRequestDto {
	this := FlexibleAssetFieldCreateDtoFlexibleAssetRequestDto{}
	return &this
}

// GetData returns the Data field value
func (o *FlexibleAssetFieldCreateDtoFlexibleAssetRequestDto) GetData() FlexibleAssetFieldCreateDto {
	if o == nil {
		var ret FlexibleAssetFieldCreateDto
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *FlexibleAssetFieldCreateDtoFlexibleAssetRequestDto) GetDataOk() (*FlexibleAssetFieldCreateDto, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *FlexibleAssetFieldCreateDtoFlexibleAssetRequestDto) SetData(v FlexibleAssetFieldCreateDto) {
	o.Data = v
}

func (o FlexibleAssetFieldCreateDtoFlexibleAssetRequestDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FlexibleAssetFieldCreateDtoFlexibleAssetRequestDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *FlexibleAssetFieldCreateDtoFlexibleAssetRequestDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFlexibleAssetFieldCreateDtoFlexibleAssetRequestDto := _FlexibleAssetFieldCreateDtoFlexibleAssetRequestDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFlexibleAssetFieldCreateDtoFlexibleAssetRequestDto)

	if err != nil {
		return err
	}

	*o = FlexibleAssetFieldCreateDtoFlexibleAssetRequestDto(varFlexibleAssetFieldCreateDtoFlexibleAssetRequestDto)

	return err
}

type NullableFlexibleAssetFieldCreateDtoFlexibleAssetRequestDto struct {
	value *FlexibleAssetFieldCreateDtoFlexibleAssetRequestDto
	isSet bool
}

func (v NullableFlexibleAssetFieldCreateDtoFlexibleAssetRequestDto) Get() *FlexibleAssetFieldCreateDtoFlexibleAssetRequestDto {
	return v.value
}

func (v *NullableFlexibleAssetFieldCreateDtoFlexibleAssetRequestDto) Set(val *FlexibleAssetFieldCreateDtoFlexibleAssetRequestDto) {
	v.value = val
	v.isSet = true
}

func (v NullableFlexibleAssetFieldCreateDtoFlexibleAssetRequestDto) IsSet() bool {
	return v.isSet
}

func (v *NullableFlexibleAssetFieldCreateDtoFlexibleAssetRequestDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFlexibleAssetFieldCreateDtoFlexibleAssetRequestDto(val *FlexibleAssetFieldCreateDtoFlexibleAssetRequestDto) *NullableFlexibleAssetFieldCreateDtoFlexibleAssetRequestDto {
	return &NullableFlexibleAssetFieldCreateDtoFlexibleAssetRequestDto{value: val, isSet: true}
}

func (v NullableFlexibleAssetFieldCreateDtoFlexibleAssetRequestDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFlexibleAssetFieldCreateDtoFlexibleAssetRequestDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
