/*
CloudRadial

The CloudRadial API is currently in development. For more information visit <a href='https://radials.io/api' target='_blank'>https://radials.io/api</a>

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloudradial

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the AssessmentImportTemplateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AssessmentImportTemplateRequest{}

// AssessmentImportTemplateRequest Request model for importing assessment questions from a template into another assessment.
type AssessmentImportTemplateRequest struct {
	// The destination assessment ID to import questions into.
	AssessmentId int32 `json:"assessmentId"`
	// The source template assessment ID to copy questions from.
	TemplateId int32 `json:"templateId"`
	// Optional scope to apply template to: \"server\", \"endpoint\", \"user\" or anything else for a single copy.
	ApplyTo NullableString `json:"applyTo,omitempty"`
}

type _AssessmentImportTemplateRequest AssessmentImportTemplateRequest

// NewAssessmentImportTemplateRequest instantiates a new AssessmentImportTemplateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssessmentImportTemplateRequest(assessmentId int32, templateId int32) *AssessmentImportTemplateRequest {
	this := AssessmentImportTemplateRequest{}
	this.AssessmentId = assessmentId
	this.TemplateId = templateId
	return &this
}

// NewAssessmentImportTemplateRequestWithDefaults instantiates a new AssessmentImportTemplateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssessmentImportTemplateRequestWithDefaults() *AssessmentImportTemplateRequest {
	this := AssessmentImportTemplateRequest{}
	return &this
}

// GetAssessmentId returns the AssessmentId field value
func (o *AssessmentImportTemplateRequest) GetAssessmentId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AssessmentId
}

// GetAssessmentIdOk returns a tuple with the AssessmentId field value
// and a boolean to check if the value has been set.
func (o *AssessmentImportTemplateRequest) GetAssessmentIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AssessmentId, true
}

// SetAssessmentId sets field value
func (o *AssessmentImportTemplateRequest) SetAssessmentId(v int32) {
	o.AssessmentId = v
}

// GetTemplateId returns the TemplateId field value
func (o *AssessmentImportTemplateRequest) GetTemplateId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TemplateId
}

// GetTemplateIdOk returns a tuple with the TemplateId field value
// and a boolean to check if the value has been set.
func (o *AssessmentImportTemplateRequest) GetTemplateIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TemplateId, true
}

// SetTemplateId sets field value
func (o *AssessmentImportTemplateRequest) SetTemplateId(v int32) {
	o.TemplateId = v
}

// GetApplyTo returns the ApplyTo field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AssessmentImportTemplateRequest) GetApplyTo() string {
	if o == nil || IsNil(o.ApplyTo.Get()) {
		var ret string
		return ret
	}
	return *o.ApplyTo.Get()
}

// GetApplyToOk returns a tuple with the ApplyTo field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AssessmentImportTemplateRequest) GetApplyToOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ApplyTo.Get(), o.ApplyTo.IsSet()
}

// HasApplyTo returns a boolean if a field has been set.
func (o *AssessmentImportTemplateRequest) HasApplyTo() bool {
	if o != nil && o.ApplyTo.IsSet() {
		return true
	}

	return false
}

// SetApplyTo gets a reference to the given NullableString and assigns it to the ApplyTo field.
func (o *AssessmentImportTemplateRequest) SetApplyTo(v string) {
	o.ApplyTo.Set(&v)
}

// SetApplyToNil sets the value for ApplyTo to be an explicit nil
func (o *AssessmentImportTemplateRequest) SetApplyToNil() {
	o.ApplyTo.Set(nil)
}

// UnsetApplyTo ensures that no value is present for ApplyTo, not even an explicit nil
func (o *AssessmentImportTemplateRequest) UnsetApplyTo() {
	o.ApplyTo.Unset()
}

func (o AssessmentImportTemplateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AssessmentImportTemplateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["assessmentId"] = o.AssessmentId
	toSerialize["templateId"] = o.TemplateId
	if o.ApplyTo.IsSet() {
		toSerialize["applyTo"] = o.ApplyTo.Get()
	}
	return toSerialize, nil
}

func (o *AssessmentImportTemplateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"assessmentId",
		"templateId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAssessmentImportTemplateRequest := _AssessmentImportTemplateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAssessmentImportTemplateRequest)

	if err != nil {
		return err
	}

	*o = AssessmentImportTemplateRequest(varAssessmentImportTemplateRequest)

	return err
}

type NullableAssessmentImportTemplateRequest struct {
	value *AssessmentImportTemplateRequest
	isSet bool
}

func (v NullableAssessmentImportTemplateRequest) Get() *AssessmentImportTemplateRequest {
	return v.value
}

func (v *NullableAssessmentImportTemplateRequest) Set(val *AssessmentImportTemplateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAssessmentImportTemplateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAssessmentImportTemplateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssessmentImportTemplateRequest(val *AssessmentImportTemplateRequest) *NullableAssessmentImportTemplateRequest {
	return &NullableAssessmentImportTemplateRequest{value: val, isSet: true}
}

func (v NullableAssessmentImportTemplateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssessmentImportTemplateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
