/*
CloudRadial

The CloudRadial API is currently in development. For more information visit <a href='https://radials.io/api' target='_blank'>https://radials.io/api</a>

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloudradial

import (
	"encoding/json"
)

// checks if the ServiceInstallResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServiceInstallResponse{}

// ServiceInstallResponse Response model for a service installation
type ServiceInstallResponse struct {
	// The endpoint ID
	EndpointId *int32 `json:"endpointId,omitempty"`
	// The service ID
	ServiceId *int32 `json:"serviceId,omitempty"`
	// The status of the service installation
	Status NullableString `json:"status,omitempty"`
	// The startup type of the service
	StartupType NullableString `json:"startupType,omitempty"`
	// The full version of the service
	FullVersion NullableString `json:"fullVersion,omitempty"`
	// The version number
	Version NullableInt32 `json:"version,omitempty"`
	// The major version number
	Major NullableInt32 `json:"major,omitempty"`
	// The minor version number
	Minor NullableInt32 `json:"minor,omitempty"`
}

// NewServiceInstallResponse instantiates a new ServiceInstallResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceInstallResponse() *ServiceInstallResponse {
	this := ServiceInstallResponse{}
	return &this
}

// NewServiceInstallResponseWithDefaults instantiates a new ServiceInstallResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceInstallResponseWithDefaults() *ServiceInstallResponse {
	this := ServiceInstallResponse{}
	return &this
}

// GetEndpointId returns the EndpointId field value if set, zero value otherwise.
func (o *ServiceInstallResponse) GetEndpointId() int32 {
	if o == nil || IsNil(o.EndpointId) {
		var ret int32
		return ret
	}
	return *o.EndpointId
}

// GetEndpointIdOk returns a tuple with the EndpointId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceInstallResponse) GetEndpointIdOk() (*int32, bool) {
	if o == nil || IsNil(o.EndpointId) {
		return nil, false
	}
	return o.EndpointId, true
}

// HasEndpointId returns a boolean if a field has been set.
func (o *ServiceInstallResponse) HasEndpointId() bool {
	if o != nil && !IsNil(o.EndpointId) {
		return true
	}

	return false
}

// SetEndpointId gets a reference to the given int32 and assigns it to the EndpointId field.
func (o *ServiceInstallResponse) SetEndpointId(v int32) {
	o.EndpointId = &v
}

// GetServiceId returns the ServiceId field value if set, zero value otherwise.
func (o *ServiceInstallResponse) GetServiceId() int32 {
	if o == nil || IsNil(o.ServiceId) {
		var ret int32
		return ret
	}
	return *o.ServiceId
}

// GetServiceIdOk returns a tuple with the ServiceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceInstallResponse) GetServiceIdOk() (*int32, bool) {
	if o == nil || IsNil(o.ServiceId) {
		return nil, false
	}
	return o.ServiceId, true
}

// HasServiceId returns a boolean if a field has been set.
func (o *ServiceInstallResponse) HasServiceId() bool {
	if o != nil && !IsNil(o.ServiceId) {
		return true
	}

	return false
}

// SetServiceId gets a reference to the given int32 and assigns it to the ServiceId field.
func (o *ServiceInstallResponse) SetServiceId(v int32) {
	o.ServiceId = &v
}

// GetStatus returns the Status field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ServiceInstallResponse) GetStatus() string {
	if o == nil || IsNil(o.Status.Get()) {
		var ret string
		return ret
	}
	return *o.Status.Get()
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ServiceInstallResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Status.Get(), o.Status.IsSet()
}

// HasStatus returns a boolean if a field has been set.
func (o *ServiceInstallResponse) HasStatus() bool {
	if o != nil && o.Status.IsSet() {
		return true
	}

	return false
}

// SetStatus gets a reference to the given NullableString and assigns it to the Status field.
func (o *ServiceInstallResponse) SetStatus(v string) {
	o.Status.Set(&v)
}

// SetStatusNil sets the value for Status to be an explicit nil
func (o *ServiceInstallResponse) SetStatusNil() {
	o.Status.Set(nil)
}

// UnsetStatus ensures that no value is present for Status, not even an explicit nil
func (o *ServiceInstallResponse) UnsetStatus() {
	o.Status.Unset()
}

// GetStartupType returns the StartupType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ServiceInstallResponse) GetStartupType() string {
	if o == nil || IsNil(o.StartupType.Get()) {
		var ret string
		return ret
	}
	return *o.StartupType.Get()
}

// GetStartupTypeOk returns a tuple with the StartupType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ServiceInstallResponse) GetStartupTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.StartupType.Get(), o.StartupType.IsSet()
}

// HasStartupType returns a boolean if a field has been set.
func (o *ServiceInstallResponse) HasStartupType() bool {
	if o != nil && o.StartupType.IsSet() {
		return true
	}

	return false
}

// SetStartupType gets a reference to the given NullableString and assigns it to the StartupType field.
func (o *ServiceInstallResponse) SetStartupType(v string) {
	o.StartupType.Set(&v)
}

// SetStartupTypeNil sets the value for StartupType to be an explicit nil
func (o *ServiceInstallResponse) SetStartupTypeNil() {
	o.StartupType.Set(nil)
}

// UnsetStartupType ensures that no value is present for StartupType, not even an explicit nil
func (o *ServiceInstallResponse) UnsetStartupType() {
	o.StartupType.Unset()
}

// GetFullVersion returns the FullVersion field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ServiceInstallResponse) GetFullVersion() string {
	if o == nil || IsNil(o.FullVersion.Get()) {
		var ret string
		return ret
	}
	return *o.FullVersion.Get()
}

// GetFullVersionOk returns a tuple with the FullVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ServiceInstallResponse) GetFullVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FullVersion.Get(), o.FullVersion.IsSet()
}

// HasFullVersion returns a boolean if a field has been set.
func (o *ServiceInstallResponse) HasFullVersion() bool {
	if o != nil && o.FullVersion.IsSet() {
		return true
	}

	return false
}

// SetFullVersion gets a reference to the given NullableString and assigns it to the FullVersion field.
func (o *ServiceInstallResponse) SetFullVersion(v string) {
	o.FullVersion.Set(&v)
}

// SetFullVersionNil sets the value for FullVersion to be an explicit nil
func (o *ServiceInstallResponse) SetFullVersionNil() {
	o.FullVersion.Set(nil)
}

// UnsetFullVersion ensures that no value is present for FullVersion, not even an explicit nil
func (o *ServiceInstallResponse) UnsetFullVersion() {
	o.FullVersion.Unset()
}

// GetVersion returns the Version field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ServiceInstallResponse) GetVersion() int32 {
	if o == nil || IsNil(o.Version.Get()) {
		var ret int32
		return ret
	}
	return *o.Version.Get()
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ServiceInstallResponse) GetVersionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Version.Get(), o.Version.IsSet()
}

// HasVersion returns a boolean if a field has been set.
func (o *ServiceInstallResponse) HasVersion() bool {
	if o != nil && o.Version.IsSet() {
		return true
	}

	return false
}

// SetVersion gets a reference to the given NullableInt32 and assigns it to the Version field.
func (o *ServiceInstallResponse) SetVersion(v int32) {
	o.Version.Set(&v)
}

// SetVersionNil sets the value for Version to be an explicit nil
func (o *ServiceInstallResponse) SetVersionNil() {
	o.Version.Set(nil)
}

// UnsetVersion ensures that no value is present for Version, not even an explicit nil
func (o *ServiceInstallResponse) UnsetVersion() {
	o.Version.Unset()
}

// GetMajor returns the Major field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ServiceInstallResponse) GetMajor() int32 {
	if o == nil || IsNil(o.Major.Get()) {
		var ret int32
		return ret
	}
	return *o.Major.Get()
}

// GetMajorOk returns a tuple with the Major field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ServiceInstallResponse) GetMajorOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Major.Get(), o.Major.IsSet()
}

// HasMajor returns a boolean if a field has been set.
func (o *ServiceInstallResponse) HasMajor() bool {
	if o != nil && o.Major.IsSet() {
		return true
	}

	return false
}

// SetMajor gets a reference to the given NullableInt32 and assigns it to the Major field.
func (o *ServiceInstallResponse) SetMajor(v int32) {
	o.Major.Set(&v)
}

// SetMajorNil sets the value for Major to be an explicit nil
func (o *ServiceInstallResponse) SetMajorNil() {
	o.Major.Set(nil)
}

// UnsetMajor ensures that no value is present for Major, not even an explicit nil
func (o *ServiceInstallResponse) UnsetMajor() {
	o.Major.Unset()
}

// GetMinor returns the Minor field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ServiceInstallResponse) GetMinor() int32 {
	if o == nil || IsNil(o.Minor.Get()) {
		var ret int32
		return ret
	}
	return *o.Minor.Get()
}

// GetMinorOk returns a tuple with the Minor field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ServiceInstallResponse) GetMinorOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Minor.Get(), o.Minor.IsSet()
}

// HasMinor returns a boolean if a field has been set.
func (o *ServiceInstallResponse) HasMinor() bool {
	if o != nil && o.Minor.IsSet() {
		return true
	}

	return false
}

// SetMinor gets a reference to the given NullableInt32 and assigns it to the Minor field.
func (o *ServiceInstallResponse) SetMinor(v int32) {
	o.Minor.Set(&v)
}

// SetMinorNil sets the value for Minor to be an explicit nil
func (o *ServiceInstallResponse) SetMinorNil() {
	o.Minor.Set(nil)
}

// UnsetMinor ensures that no value is present for Minor, not even an explicit nil
func (o *ServiceInstallResponse) UnsetMinor() {
	o.Minor.Unset()
}

func (o ServiceInstallResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServiceInstallResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EndpointId) {
		toSerialize["endpointId"] = o.EndpointId
	}
	if !IsNil(o.ServiceId) {
		toSerialize["serviceId"] = o.ServiceId
	}
	if o.Status.IsSet() {
		toSerialize["status"] = o.Status.Get()
	}
	if o.StartupType.IsSet() {
		toSerialize["startupType"] = o.StartupType.Get()
	}
	if o.FullVersion.IsSet() {
		toSerialize["fullVersion"] = o.FullVersion.Get()
	}
	if o.Version.IsSet() {
		toSerialize["version"] = o.Version.Get()
	}
	if o.Major.IsSet() {
		toSerialize["major"] = o.Major.Get()
	}
	if o.Minor.IsSet() {
		toSerialize["minor"] = o.Minor.Get()
	}
	return toSerialize, nil
}

type NullableServiceInstallResponse struct {
	value *ServiceInstallResponse
	isSet bool
}

func (v NullableServiceInstallResponse) Get() *ServiceInstallResponse {
	return v.value
}

func (v *NullableServiceInstallResponse) Set(val *ServiceInstallResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceInstallResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceInstallResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceInstallResponse(val *ServiceInstallResponse) *NullableServiceInstallResponse {
	return &NullableServiceInstallResponse{value: val, isSet: true}
}

func (v NullableServiceInstallResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceInstallResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
