/*
CloudRadial

The CloudRadial API is currently in development. For more information visit <a href='https://radials.io/api' target='_blank'>https://radials.io/api</a>

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncentral

import (
	"encoding/json"
	"fmt"
)

// MatrixStatus the model 'MatrixStatus'
type MatrixStatus int32

// List of MatrixStatus
const (
	_0  MatrixStatus = 0
	_1  MatrixStatus = 1
	_10 MatrixStatus = 10
	_20 MatrixStatus = 20
	_30 MatrixStatus = 30
	_40 MatrixStatus = 40
	_50 MatrixStatus = 50
)

// All allowed values of MatrixStatus enum
var AllowedMatrixStatusEnumValues = []MatrixStatus{
	0,
	1,
	10,
	20,
	30,
	40,
	50,
}

func (v *MatrixStatus) UnmarshalJSON(src []byte) error {
	var value int32
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := MatrixStatus(value)
	for _, existing := range AllowedMatrixStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid MatrixStatus", value)
}

// NewMatrixStatusFromValue returns a pointer to a valid MatrixStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewMatrixStatusFromValue(v int32) (*MatrixStatus, error) {
	ev := MatrixStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for MatrixStatus: valid values are %v", v, AllowedMatrixStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v MatrixStatus) IsValid() bool {
	for _, existing := range AllowedMatrixStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to MatrixStatus value
func (v MatrixStatus) Ptr() *MatrixStatus {
	return &v
}

type NullableMatrixStatus struct {
	value *MatrixStatus
	isSet bool
}

func (v NullableMatrixStatus) Get() *MatrixStatus {
	return v.value
}

func (v *NullableMatrixStatus) Set(val *MatrixStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableMatrixStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableMatrixStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMatrixStatus(val *MatrixStatus) *NullableMatrixStatus {
	return &NullableMatrixStatus{value: val, isSet: true}
}

func (v NullableMatrixStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMatrixStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
