/*
CloudRadial

The CloudRadial API is currently in development. For more information visit <a href='https://radials.io/api' target='_blank'>https://radials.io/api</a>

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncentral

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CompanyGroupCompanyRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CompanyGroupCompanyRequest{}

// CompanyGroupCompanyRequest Request model for creating or updating company group companies associated with partner groups
type CompanyGroupCompanyRequest struct {
	// Company Group ID
	CompanyGroupId int32 `json:"companyGroupId"`
	// Company ID
	CompanyId int32 `json:"companyId"`
}

type _CompanyGroupCompanyRequest CompanyGroupCompanyRequest

// NewCompanyGroupCompanyRequest instantiates a new CompanyGroupCompanyRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCompanyGroupCompanyRequest(companyGroupId int32, companyId int32) *CompanyGroupCompanyRequest {
	this := CompanyGroupCompanyRequest{}
	this.CompanyGroupId = companyGroupId
	this.CompanyId = companyId
	return &this
}

// NewCompanyGroupCompanyRequestWithDefaults instantiates a new CompanyGroupCompanyRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCompanyGroupCompanyRequestWithDefaults() *CompanyGroupCompanyRequest {
	this := CompanyGroupCompanyRequest{}
	return &this
}

// GetCompanyGroupId returns the CompanyGroupId field value
func (o *CompanyGroupCompanyRequest) GetCompanyGroupId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CompanyGroupId
}

// GetCompanyGroupIdOk returns a tuple with the CompanyGroupId field value
// and a boolean to check if the value has been set.
func (o *CompanyGroupCompanyRequest) GetCompanyGroupIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CompanyGroupId, true
}

// SetCompanyGroupId sets field value
func (o *CompanyGroupCompanyRequest) SetCompanyGroupId(v int32) {
	o.CompanyGroupId = v
}

// GetCompanyId returns the CompanyId field value
func (o *CompanyGroupCompanyRequest) GetCompanyId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CompanyId
}

// GetCompanyIdOk returns a tuple with the CompanyId field value
// and a boolean to check if the value has been set.
func (o *CompanyGroupCompanyRequest) GetCompanyIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CompanyId, true
}

// SetCompanyId sets field value
func (o *CompanyGroupCompanyRequest) SetCompanyId(v int32) {
	o.CompanyId = v
}

func (o CompanyGroupCompanyRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CompanyGroupCompanyRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["companyGroupId"] = o.CompanyGroupId
	toSerialize["companyId"] = o.CompanyId
	return toSerialize, nil
}

func (o *CompanyGroupCompanyRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"companyGroupId",
		"companyId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCompanyGroupCompanyRequest := _CompanyGroupCompanyRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCompanyGroupCompanyRequest)

	if err != nil {
		return err
	}

	*o = CompanyGroupCompanyRequest(varCompanyGroupCompanyRequest)

	return err
}

type NullableCompanyGroupCompanyRequest struct {
	value *CompanyGroupCompanyRequest
	isSet bool
}

func (v NullableCompanyGroupCompanyRequest) Get() *CompanyGroupCompanyRequest {
	return v.value
}

func (v *NullableCompanyGroupCompanyRequest) Set(val *CompanyGroupCompanyRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCompanyGroupCompanyRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCompanyGroupCompanyRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCompanyGroupCompanyRequest(val *CompanyGroupCompanyRequest) *NullableCompanyGroupCompanyRequest {
	return &NullableCompanyGroupCompanyRequest{value: val, isSet: true}
}

func (v NullableCompanyGroupCompanyRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCompanyGroupCompanyRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
