/*
CloudRadial

The CloudRadial API is currently in development. For more information visit <a href='https://radials.io/api' target='_blank'>https://radials.io/api</a>

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloudradial

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the FlexibleAssetBulkUpdateDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FlexibleAssetBulkUpdateDto{}

// FlexibleAssetBulkUpdateDto struct for FlexibleAssetBulkUpdateDto
type FlexibleAssetBulkUpdateDto struct {
	Attributes *FlexibleAssetAttributesBulkUpdateDto `json:"attributes,omitempty"`
	Type       string                                `json:"type"`
}

type _FlexibleAssetBulkUpdateDto FlexibleAssetBulkUpdateDto

// NewFlexibleAssetBulkUpdateDto instantiates a new FlexibleAssetBulkUpdateDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFlexibleAssetBulkUpdateDto(type_ string) *FlexibleAssetBulkUpdateDto {
	this := FlexibleAssetBulkUpdateDto{}
	this.Type = type_
	return &this
}

// NewFlexibleAssetBulkUpdateDtoWithDefaults instantiates a new FlexibleAssetBulkUpdateDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFlexibleAssetBulkUpdateDtoWithDefaults() *FlexibleAssetBulkUpdateDto {
	this := FlexibleAssetBulkUpdateDto{}
	return &this
}

// GetAttributes returns the Attributes field value if set, zero value otherwise.
func (o *FlexibleAssetBulkUpdateDto) GetAttributes() FlexibleAssetAttributesBulkUpdateDto {
	if o == nil || IsNil(o.Attributes) {
		var ret FlexibleAssetAttributesBulkUpdateDto
		return ret
	}
	return *o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FlexibleAssetBulkUpdateDto) GetAttributesOk() (*FlexibleAssetAttributesBulkUpdateDto, bool) {
	if o == nil || IsNil(o.Attributes) {
		return nil, false
	}
	return o.Attributes, true
}

// HasAttributes returns a boolean if a field has been set.
func (o *FlexibleAssetBulkUpdateDto) HasAttributes() bool {
	if o != nil && !IsNil(o.Attributes) {
		return true
	}

	return false
}

// SetAttributes gets a reference to the given FlexibleAssetAttributesBulkUpdateDto and assigns it to the Attributes field.
func (o *FlexibleAssetBulkUpdateDto) SetAttributes(v FlexibleAssetAttributesBulkUpdateDto) {
	o.Attributes = &v
}

// GetType returns the Type field value
func (o *FlexibleAssetBulkUpdateDto) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *FlexibleAssetBulkUpdateDto) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *FlexibleAssetBulkUpdateDto) SetType(v string) {
	o.Type = v
}

func (o FlexibleAssetBulkUpdateDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FlexibleAssetBulkUpdateDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Attributes) {
		toSerialize["attributes"] = o.Attributes
	}
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *FlexibleAssetBulkUpdateDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFlexibleAssetBulkUpdateDto := _FlexibleAssetBulkUpdateDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFlexibleAssetBulkUpdateDto)

	if err != nil {
		return err
	}

	*o = FlexibleAssetBulkUpdateDto(varFlexibleAssetBulkUpdateDto)

	return err
}

type NullableFlexibleAssetBulkUpdateDto struct {
	value *FlexibleAssetBulkUpdateDto
	isSet bool
}

func (v NullableFlexibleAssetBulkUpdateDto) Get() *FlexibleAssetBulkUpdateDto {
	return v.value
}

func (v *NullableFlexibleAssetBulkUpdateDto) Set(val *FlexibleAssetBulkUpdateDto) {
	v.value = val
	v.isSet = true
}

func (v NullableFlexibleAssetBulkUpdateDto) IsSet() bool {
	return v.isSet
}

func (v *NullableFlexibleAssetBulkUpdateDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFlexibleAssetBulkUpdateDto(val *FlexibleAssetBulkUpdateDto) *NullableFlexibleAssetBulkUpdateDto {
	return &NullableFlexibleAssetBulkUpdateDto{value: val, isSet: true}
}

func (v NullableFlexibleAssetBulkUpdateDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFlexibleAssetBulkUpdateDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
