/*
CloudRadial

The CloudRadial API is currently in development. For more information visit <a href='https://radials.io/api' target='_blank'>https://radials.io/api</a>

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncentral

import (
	"encoding/json"
	"time"
)

// checks if the CompanyGroupResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CompanyGroupResponse{}

// CompanyGroupResponse struct for CompanyGroupResponse
type CompanyGroupResponse struct {
	// Company Group ID
	CompanyGroupId *int32         `json:"companyGroupId,omitempty"`
	Group          NullableString `json:"group,omitempty"`
	DateCreated    *time.Time     `json:"dateCreated,omitempty"`
	DateModified   *time.Time     `json:"dateModified,omitempty"`
}

// NewCompanyGroupResponse instantiates a new CompanyGroupResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCompanyGroupResponse() *CompanyGroupResponse {
	this := CompanyGroupResponse{}
	return &this
}

// NewCompanyGroupResponseWithDefaults instantiates a new CompanyGroupResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCompanyGroupResponseWithDefaults() *CompanyGroupResponse {
	this := CompanyGroupResponse{}
	return &this
}

// GetCompanyGroupId returns the CompanyGroupId field value if set, zero value otherwise.
func (o *CompanyGroupResponse) GetCompanyGroupId() int32 {
	if o == nil || IsNil(o.CompanyGroupId) {
		var ret int32
		return ret
	}
	return *o.CompanyGroupId
}

// GetCompanyGroupIdOk returns a tuple with the CompanyGroupId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyGroupResponse) GetCompanyGroupIdOk() (*int32, bool) {
	if o == nil || IsNil(o.CompanyGroupId) {
		return nil, false
	}
	return o.CompanyGroupId, true
}

// HasCompanyGroupId returns a boolean if a field has been set.
func (o *CompanyGroupResponse) HasCompanyGroupId() bool {
	if o != nil && !IsNil(o.CompanyGroupId) {
		return true
	}

	return false
}

// SetCompanyGroupId gets a reference to the given int32 and assigns it to the CompanyGroupId field.
func (o *CompanyGroupResponse) SetCompanyGroupId(v int32) {
	o.CompanyGroupId = &v
}

// GetGroup returns the Group field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CompanyGroupResponse) GetGroup() string {
	if o == nil || IsNil(o.Group.Get()) {
		var ret string
		return ret
	}
	return *o.Group.Get()
}

// GetGroupOk returns a tuple with the Group field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CompanyGroupResponse) GetGroupOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Group.Get(), o.Group.IsSet()
}

// HasGroup returns a boolean if a field has been set.
func (o *CompanyGroupResponse) HasGroup() bool {
	if o != nil && o.Group.IsSet() {
		return true
	}

	return false
}

// SetGroup gets a reference to the given NullableString and assigns it to the Group field.
func (o *CompanyGroupResponse) SetGroup(v string) {
	o.Group.Set(&v)
}

// SetGroupNil sets the value for Group to be an explicit nil
func (o *CompanyGroupResponse) SetGroupNil() {
	o.Group.Set(nil)
}

// UnsetGroup ensures that no value is present for Group, not even an explicit nil
func (o *CompanyGroupResponse) UnsetGroup() {
	o.Group.Unset()
}

// GetDateCreated returns the DateCreated field value if set, zero value otherwise.
func (o *CompanyGroupResponse) GetDateCreated() time.Time {
	if o == nil || IsNil(o.DateCreated) {
		var ret time.Time
		return ret
	}
	return *o.DateCreated
}

// GetDateCreatedOk returns a tuple with the DateCreated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyGroupResponse) GetDateCreatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.DateCreated) {
		return nil, false
	}
	return o.DateCreated, true
}

// HasDateCreated returns a boolean if a field has been set.
func (o *CompanyGroupResponse) HasDateCreated() bool {
	if o != nil && !IsNil(o.DateCreated) {
		return true
	}

	return false
}

// SetDateCreated gets a reference to the given time.Time and assigns it to the DateCreated field.
func (o *CompanyGroupResponse) SetDateCreated(v time.Time) {
	o.DateCreated = &v
}

// GetDateModified returns the DateModified field value if set, zero value otherwise.
func (o *CompanyGroupResponse) GetDateModified() time.Time {
	if o == nil || IsNil(o.DateModified) {
		var ret time.Time
		return ret
	}
	return *o.DateModified
}

// GetDateModifiedOk returns a tuple with the DateModified field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyGroupResponse) GetDateModifiedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.DateModified) {
		return nil, false
	}
	return o.DateModified, true
}

// HasDateModified returns a boolean if a field has been set.
func (o *CompanyGroupResponse) HasDateModified() bool {
	if o != nil && !IsNil(o.DateModified) {
		return true
	}

	return false
}

// SetDateModified gets a reference to the given time.Time and assigns it to the DateModified field.
func (o *CompanyGroupResponse) SetDateModified(v time.Time) {
	o.DateModified = &v
}

func (o CompanyGroupResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CompanyGroupResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CompanyGroupId) {
		toSerialize["companyGroupId"] = o.CompanyGroupId
	}
	if o.Group.IsSet() {
		toSerialize["group"] = o.Group.Get()
	}
	if !IsNil(o.DateCreated) {
		toSerialize["dateCreated"] = o.DateCreated
	}
	if !IsNil(o.DateModified) {
		toSerialize["dateModified"] = o.DateModified
	}
	return toSerialize, nil
}

type NullableCompanyGroupResponse struct {
	value *CompanyGroupResponse
	isSet bool
}

func (v NullableCompanyGroupResponse) Get() *CompanyGroupResponse {
	return v.value
}

func (v *NullableCompanyGroupResponse) Set(val *CompanyGroupResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCompanyGroupResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCompanyGroupResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCompanyGroupResponse(val *CompanyGroupResponse) *NullableCompanyGroupResponse {
	return &NullableCompanyGroupResponse{value: val, isSet: true}
}

func (v NullableCompanyGroupResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCompanyGroupResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
