/*
CloudRadial

The CloudRadial API is currently in development. For more information visit <a href='https://radials.io/api' target='_blank'>https://radials.io/api</a>

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloudradial

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CompanyGroupRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CompanyGroupRequest{}

// CompanyGroupRequest struct for CompanyGroupRequest
type CompanyGroupRequest struct {
	Group string `json:"group"`
}

type _CompanyGroupRequest CompanyGroupRequest

// NewCompanyGroupRequest instantiates a new CompanyGroupRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCompanyGroupRequest(group string) *CompanyGroupRequest {
	this := CompanyGroupRequest{}
	this.Group = group
	return &this
}

// NewCompanyGroupRequestWithDefaults instantiates a new CompanyGroupRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCompanyGroupRequestWithDefaults() *CompanyGroupRequest {
	this := CompanyGroupRequest{}
	return &this
}

// GetGroup returns the Group field value
func (o *CompanyGroupRequest) GetGroup() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Group
}

// GetGroupOk returns a tuple with the Group field value
// and a boolean to check if the value has been set.
func (o *CompanyGroupRequest) GetGroupOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Group, true
}

// SetGroup sets field value
func (o *CompanyGroupRequest) SetGroup(v string) {
	o.Group = v
}

func (o CompanyGroupRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CompanyGroupRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["group"] = o.Group
	return toSerialize, nil
}

func (o *CompanyGroupRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"group",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCompanyGroupRequest := _CompanyGroupRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCompanyGroupRequest)

	if err != nil {
		return err
	}

	*o = CompanyGroupRequest(varCompanyGroupRequest)

	return err
}

type NullableCompanyGroupRequest struct {
	value *CompanyGroupRequest
	isSet bool
}

func (v NullableCompanyGroupRequest) Get() *CompanyGroupRequest {
	return v.value
}

func (v *NullableCompanyGroupRequest) Set(val *CompanyGroupRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCompanyGroupRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCompanyGroupRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCompanyGroupRequest(val *CompanyGroupRequest) *NullableCompanyGroupRequest {
	return &NullableCompanyGroupRequest{value: val, isSet: true}
}

func (v NullableCompanyGroupRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCompanyGroupRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
