/*
CloudRadial

The CloudRadial API is currently in development. For more information visit <a href='https://radials.io/api' target='_blank'>https://radials.io/api</a>

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloudradial

import (
	"encoding/json"
)

// checks if the CompanyCatalogQuestionHideConditionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CompanyCatalogQuestionHideConditionResponse{}

// CompanyCatalogQuestionHideConditionResponse struct for CompanyCatalogQuestionHideConditionResponse
type CompanyCatalogQuestionHideConditionResponse struct {
	QuestionId *int32         `json:"questionId,omitempty"`
	Value      NullableString `json:"value,omitempty"`
	Operator   NullableString `json:"operator,omitempty"`
}

// NewCompanyCatalogQuestionHideConditionResponse instantiates a new CompanyCatalogQuestionHideConditionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCompanyCatalogQuestionHideConditionResponse() *CompanyCatalogQuestionHideConditionResponse {
	this := CompanyCatalogQuestionHideConditionResponse{}
	return &this
}

// NewCompanyCatalogQuestionHideConditionResponseWithDefaults instantiates a new CompanyCatalogQuestionHideConditionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCompanyCatalogQuestionHideConditionResponseWithDefaults() *CompanyCatalogQuestionHideConditionResponse {
	this := CompanyCatalogQuestionHideConditionResponse{}
	return &this
}

// GetQuestionId returns the QuestionId field value if set, zero value otherwise.
func (o *CompanyCatalogQuestionHideConditionResponse) GetQuestionId() int32 {
	if o == nil || IsNil(o.QuestionId) {
		var ret int32
		return ret
	}
	return *o.QuestionId
}

// GetQuestionIdOk returns a tuple with the QuestionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyCatalogQuestionHideConditionResponse) GetQuestionIdOk() (*int32, bool) {
	if o == nil || IsNil(o.QuestionId) {
		return nil, false
	}
	return o.QuestionId, true
}

// HasQuestionId returns a boolean if a field has been set.
func (o *CompanyCatalogQuestionHideConditionResponse) HasQuestionId() bool {
	if o != nil && !IsNil(o.QuestionId) {
		return true
	}

	return false
}

// SetQuestionId gets a reference to the given int32 and assigns it to the QuestionId field.
func (o *CompanyCatalogQuestionHideConditionResponse) SetQuestionId(v int32) {
	o.QuestionId = &v
}

// GetValue returns the Value field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CompanyCatalogQuestionHideConditionResponse) GetValue() string {
	if o == nil || IsNil(o.Value.Get()) {
		var ret string
		return ret
	}
	return *o.Value.Get()
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CompanyCatalogQuestionHideConditionResponse) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Value.Get(), o.Value.IsSet()
}

// HasValue returns a boolean if a field has been set.
func (o *CompanyCatalogQuestionHideConditionResponse) HasValue() bool {
	if o != nil && o.Value.IsSet() {
		return true
	}

	return false
}

// SetValue gets a reference to the given NullableString and assigns it to the Value field.
func (o *CompanyCatalogQuestionHideConditionResponse) SetValue(v string) {
	o.Value.Set(&v)
}

// SetValueNil sets the value for Value to be an explicit nil
func (o *CompanyCatalogQuestionHideConditionResponse) SetValueNil() {
	o.Value.Set(nil)
}

// UnsetValue ensures that no value is present for Value, not even an explicit nil
func (o *CompanyCatalogQuestionHideConditionResponse) UnsetValue() {
	o.Value.Unset()
}

// GetOperator returns the Operator field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CompanyCatalogQuestionHideConditionResponse) GetOperator() string {
	if o == nil || IsNil(o.Operator.Get()) {
		var ret string
		return ret
	}
	return *o.Operator.Get()
}

// GetOperatorOk returns a tuple with the Operator field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CompanyCatalogQuestionHideConditionResponse) GetOperatorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Operator.Get(), o.Operator.IsSet()
}

// HasOperator returns a boolean if a field has been set.
func (o *CompanyCatalogQuestionHideConditionResponse) HasOperator() bool {
	if o != nil && o.Operator.IsSet() {
		return true
	}

	return false
}

// SetOperator gets a reference to the given NullableString and assigns it to the Operator field.
func (o *CompanyCatalogQuestionHideConditionResponse) SetOperator(v string) {
	o.Operator.Set(&v)
}

// SetOperatorNil sets the value for Operator to be an explicit nil
func (o *CompanyCatalogQuestionHideConditionResponse) SetOperatorNil() {
	o.Operator.Set(nil)
}

// UnsetOperator ensures that no value is present for Operator, not even an explicit nil
func (o *CompanyCatalogQuestionHideConditionResponse) UnsetOperator() {
	o.Operator.Unset()
}

func (o CompanyCatalogQuestionHideConditionResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CompanyCatalogQuestionHideConditionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.QuestionId) {
		toSerialize["questionId"] = o.QuestionId
	}
	if o.Value.IsSet() {
		toSerialize["value"] = o.Value.Get()
	}
	if o.Operator.IsSet() {
		toSerialize["operator"] = o.Operator.Get()
	}
	return toSerialize, nil
}

type NullableCompanyCatalogQuestionHideConditionResponse struct {
	value *CompanyCatalogQuestionHideConditionResponse
	isSet bool
}

func (v NullableCompanyCatalogQuestionHideConditionResponse) Get() *CompanyCatalogQuestionHideConditionResponse {
	return v.value
}

func (v *NullableCompanyCatalogQuestionHideConditionResponse) Set(val *CompanyCatalogQuestionHideConditionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCompanyCatalogQuestionHideConditionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCompanyCatalogQuestionHideConditionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCompanyCatalogQuestionHideConditionResponse(val *CompanyCatalogQuestionHideConditionResponse) *NullableCompanyCatalogQuestionHideConditionResponse {
	return &NullableCompanyCatalogQuestionHideConditionResponse{value: val, isSet: true}
}

func (v NullableCompanyCatalogQuestionHideConditionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCompanyCatalogQuestionHideConditionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
