/*
CloudRadial

The CloudRadial API is currently in development. For more information visit <a href='https://radials.io/api' target='_blank'>https://radials.io/api</a>

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloudradial

import (
	"encoding/json"
	"time"
)

// checks if the CourseLessonHistoryResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CourseLessonHistoryResponse{}

// CourseLessonHistoryResponse Response model for course lesson history
type CourseLessonHistoryResponse struct {
	// Course lesson history composite key identifier (for client reference)  Format: {CourseId}-{ApplicationUserId}-{CourseLessonId}
	CourseLessonHistoryId NullableString `json:"courseLessonHistoryId,omitempty"`
	// Course ID
	CourseId *int32 `json:"courseId,omitempty"`
	// Application User ID
	ApplicationUserId NullableString `json:"applicationUserId,omitempty"`
	// Course lesson ID
	CourseLessonId *int32 `json:"courseLessonId,omitempty"`
	// Company ID
	CompanyId *int32 `json:"companyId,omitempty"`
	// Completed score for the lesson
	CompletedScore *int32 `json:"completedScore,omitempty"`
	// Date the history record was created
	DateCreated *time.Time `json:"dateCreated,omitempty"`
	// Date the history record was last modified
	DateModified *time.Time `json:"dateModified,omitempty"`
	// Whether the history record is soft deleted
	IsDeleted *bool `json:"isDeleted,omitempty"`
}

// NewCourseLessonHistoryResponse instantiates a new CourseLessonHistoryResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCourseLessonHistoryResponse() *CourseLessonHistoryResponse {
	this := CourseLessonHistoryResponse{}
	return &this
}

// NewCourseLessonHistoryResponseWithDefaults instantiates a new CourseLessonHistoryResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCourseLessonHistoryResponseWithDefaults() *CourseLessonHistoryResponse {
	this := CourseLessonHistoryResponse{}
	return &this
}

// GetCourseLessonHistoryId returns the CourseLessonHistoryId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CourseLessonHistoryResponse) GetCourseLessonHistoryId() string {
	if o == nil || IsNil(o.CourseLessonHistoryId.Get()) {
		var ret string
		return ret
	}
	return *o.CourseLessonHistoryId.Get()
}

// GetCourseLessonHistoryIdOk returns a tuple with the CourseLessonHistoryId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CourseLessonHistoryResponse) GetCourseLessonHistoryIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CourseLessonHistoryId.Get(), o.CourseLessonHistoryId.IsSet()
}

// HasCourseLessonHistoryId returns a boolean if a field has been set.
func (o *CourseLessonHistoryResponse) HasCourseLessonHistoryId() bool {
	if o != nil && o.CourseLessonHistoryId.IsSet() {
		return true
	}

	return false
}

// SetCourseLessonHistoryId gets a reference to the given NullableString and assigns it to the CourseLessonHistoryId field.
func (o *CourseLessonHistoryResponse) SetCourseLessonHistoryId(v string) {
	o.CourseLessonHistoryId.Set(&v)
}

// SetCourseLessonHistoryIdNil sets the value for CourseLessonHistoryId to be an explicit nil
func (o *CourseLessonHistoryResponse) SetCourseLessonHistoryIdNil() {
	o.CourseLessonHistoryId.Set(nil)
}

// UnsetCourseLessonHistoryId ensures that no value is present for CourseLessonHistoryId, not even an explicit nil
func (o *CourseLessonHistoryResponse) UnsetCourseLessonHistoryId() {
	o.CourseLessonHistoryId.Unset()
}

// GetCourseId returns the CourseId field value if set, zero value otherwise.
func (o *CourseLessonHistoryResponse) GetCourseId() int32 {
	if o == nil || IsNil(o.CourseId) {
		var ret int32
		return ret
	}
	return *o.CourseId
}

// GetCourseIdOk returns a tuple with the CourseId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CourseLessonHistoryResponse) GetCourseIdOk() (*int32, bool) {
	if o == nil || IsNil(o.CourseId) {
		return nil, false
	}
	return o.CourseId, true
}

// HasCourseId returns a boolean if a field has been set.
func (o *CourseLessonHistoryResponse) HasCourseId() bool {
	if o != nil && !IsNil(o.CourseId) {
		return true
	}

	return false
}

// SetCourseId gets a reference to the given int32 and assigns it to the CourseId field.
func (o *CourseLessonHistoryResponse) SetCourseId(v int32) {
	o.CourseId = &v
}

// GetApplicationUserId returns the ApplicationUserId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CourseLessonHistoryResponse) GetApplicationUserId() string {
	if o == nil || IsNil(o.ApplicationUserId.Get()) {
		var ret string
		return ret
	}
	return *o.ApplicationUserId.Get()
}

// GetApplicationUserIdOk returns a tuple with the ApplicationUserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CourseLessonHistoryResponse) GetApplicationUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ApplicationUserId.Get(), o.ApplicationUserId.IsSet()
}

// HasApplicationUserId returns a boolean if a field has been set.
func (o *CourseLessonHistoryResponse) HasApplicationUserId() bool {
	if o != nil && o.ApplicationUserId.IsSet() {
		return true
	}

	return false
}

// SetApplicationUserId gets a reference to the given NullableString and assigns it to the ApplicationUserId field.
func (o *CourseLessonHistoryResponse) SetApplicationUserId(v string) {
	o.ApplicationUserId.Set(&v)
}

// SetApplicationUserIdNil sets the value for ApplicationUserId to be an explicit nil
func (o *CourseLessonHistoryResponse) SetApplicationUserIdNil() {
	o.ApplicationUserId.Set(nil)
}

// UnsetApplicationUserId ensures that no value is present for ApplicationUserId, not even an explicit nil
func (o *CourseLessonHistoryResponse) UnsetApplicationUserId() {
	o.ApplicationUserId.Unset()
}

// GetCourseLessonId returns the CourseLessonId field value if set, zero value otherwise.
func (o *CourseLessonHistoryResponse) GetCourseLessonId() int32 {
	if o == nil || IsNil(o.CourseLessonId) {
		var ret int32
		return ret
	}
	return *o.CourseLessonId
}

// GetCourseLessonIdOk returns a tuple with the CourseLessonId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CourseLessonHistoryResponse) GetCourseLessonIdOk() (*int32, bool) {
	if o == nil || IsNil(o.CourseLessonId) {
		return nil, false
	}
	return o.CourseLessonId, true
}

// HasCourseLessonId returns a boolean if a field has been set.
func (o *CourseLessonHistoryResponse) HasCourseLessonId() bool {
	if o != nil && !IsNil(o.CourseLessonId) {
		return true
	}

	return false
}

// SetCourseLessonId gets a reference to the given int32 and assigns it to the CourseLessonId field.
func (o *CourseLessonHistoryResponse) SetCourseLessonId(v int32) {
	o.CourseLessonId = &v
}

// GetCompanyId returns the CompanyId field value if set, zero value otherwise.
func (o *CourseLessonHistoryResponse) GetCompanyId() int32 {
	if o == nil || IsNil(o.CompanyId) {
		var ret int32
		return ret
	}
	return *o.CompanyId
}

// GetCompanyIdOk returns a tuple with the CompanyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CourseLessonHistoryResponse) GetCompanyIdOk() (*int32, bool) {
	if o == nil || IsNil(o.CompanyId) {
		return nil, false
	}
	return o.CompanyId, true
}

// HasCompanyId returns a boolean if a field has been set.
func (o *CourseLessonHistoryResponse) HasCompanyId() bool {
	if o != nil && !IsNil(o.CompanyId) {
		return true
	}

	return false
}

// SetCompanyId gets a reference to the given int32 and assigns it to the CompanyId field.
func (o *CourseLessonHistoryResponse) SetCompanyId(v int32) {
	o.CompanyId = &v
}

// GetCompletedScore returns the CompletedScore field value if set, zero value otherwise.
func (o *CourseLessonHistoryResponse) GetCompletedScore() int32 {
	if o == nil || IsNil(o.CompletedScore) {
		var ret int32
		return ret
	}
	return *o.CompletedScore
}

// GetCompletedScoreOk returns a tuple with the CompletedScore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CourseLessonHistoryResponse) GetCompletedScoreOk() (*int32, bool) {
	if o == nil || IsNil(o.CompletedScore) {
		return nil, false
	}
	return o.CompletedScore, true
}

// HasCompletedScore returns a boolean if a field has been set.
func (o *CourseLessonHistoryResponse) HasCompletedScore() bool {
	if o != nil && !IsNil(o.CompletedScore) {
		return true
	}

	return false
}

// SetCompletedScore gets a reference to the given int32 and assigns it to the CompletedScore field.
func (o *CourseLessonHistoryResponse) SetCompletedScore(v int32) {
	o.CompletedScore = &v
}

// GetDateCreated returns the DateCreated field value if set, zero value otherwise.
func (o *CourseLessonHistoryResponse) GetDateCreated() time.Time {
	if o == nil || IsNil(o.DateCreated) {
		var ret time.Time
		return ret
	}
	return *o.DateCreated
}

// GetDateCreatedOk returns a tuple with the DateCreated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CourseLessonHistoryResponse) GetDateCreatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.DateCreated) {
		return nil, false
	}
	return o.DateCreated, true
}

// HasDateCreated returns a boolean if a field has been set.
func (o *CourseLessonHistoryResponse) HasDateCreated() bool {
	if o != nil && !IsNil(o.DateCreated) {
		return true
	}

	return false
}

// SetDateCreated gets a reference to the given time.Time and assigns it to the DateCreated field.
func (o *CourseLessonHistoryResponse) SetDateCreated(v time.Time) {
	o.DateCreated = &v
}

// GetDateModified returns the DateModified field value if set, zero value otherwise.
func (o *CourseLessonHistoryResponse) GetDateModified() time.Time {
	if o == nil || IsNil(o.DateModified) {
		var ret time.Time
		return ret
	}
	return *o.DateModified
}

// GetDateModifiedOk returns a tuple with the DateModified field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CourseLessonHistoryResponse) GetDateModifiedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.DateModified) {
		return nil, false
	}
	return o.DateModified, true
}

// HasDateModified returns a boolean if a field has been set.
func (o *CourseLessonHistoryResponse) HasDateModified() bool {
	if o != nil && !IsNil(o.DateModified) {
		return true
	}

	return false
}

// SetDateModified gets a reference to the given time.Time and assigns it to the DateModified field.
func (o *CourseLessonHistoryResponse) SetDateModified(v time.Time) {
	o.DateModified = &v
}

// GetIsDeleted returns the IsDeleted field value if set, zero value otherwise.
func (o *CourseLessonHistoryResponse) GetIsDeleted() bool {
	if o == nil || IsNil(o.IsDeleted) {
		var ret bool
		return ret
	}
	return *o.IsDeleted
}

// GetIsDeletedOk returns a tuple with the IsDeleted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CourseLessonHistoryResponse) GetIsDeletedOk() (*bool, bool) {
	if o == nil || IsNil(o.IsDeleted) {
		return nil, false
	}
	return o.IsDeleted, true
}

// HasIsDeleted returns a boolean if a field has been set.
func (o *CourseLessonHistoryResponse) HasIsDeleted() bool {
	if o != nil && !IsNil(o.IsDeleted) {
		return true
	}

	return false
}

// SetIsDeleted gets a reference to the given bool and assigns it to the IsDeleted field.
func (o *CourseLessonHistoryResponse) SetIsDeleted(v bool) {
	o.IsDeleted = &v
}

func (o CourseLessonHistoryResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CourseLessonHistoryResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.CourseLessonHistoryId.IsSet() {
		toSerialize["courseLessonHistoryId"] = o.CourseLessonHistoryId.Get()
	}
	if !IsNil(o.CourseId) {
		toSerialize["courseId"] = o.CourseId
	}
	if o.ApplicationUserId.IsSet() {
		toSerialize["applicationUserId"] = o.ApplicationUserId.Get()
	}
	if !IsNil(o.CourseLessonId) {
		toSerialize["courseLessonId"] = o.CourseLessonId
	}
	if !IsNil(o.CompanyId) {
		toSerialize["companyId"] = o.CompanyId
	}
	if !IsNil(o.CompletedScore) {
		toSerialize["completedScore"] = o.CompletedScore
	}
	if !IsNil(o.DateCreated) {
		toSerialize["dateCreated"] = o.DateCreated
	}
	if !IsNil(o.DateModified) {
		toSerialize["dateModified"] = o.DateModified
	}
	if !IsNil(o.IsDeleted) {
		toSerialize["isDeleted"] = o.IsDeleted
	}
	return toSerialize, nil
}

type NullableCourseLessonHistoryResponse struct {
	value *CourseLessonHistoryResponse
	isSet bool
}

func (v NullableCourseLessonHistoryResponse) Get() *CourseLessonHistoryResponse {
	return v.value
}

func (v *NullableCourseLessonHistoryResponse) Set(val *CourseLessonHistoryResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCourseLessonHistoryResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCourseLessonHistoryResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCourseLessonHistoryResponse(val *CourseLessonHistoryResponse) *NullableCourseLessonHistoryResponse {
	return &NullableCourseLessonHistoryResponse{value: val, isSet: true}
}

func (v NullableCourseLessonHistoryResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCourseLessonHistoryResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
