/*
CloudRadial

The CloudRadial API is currently in development. For more information visit <a href='https://radials.io/api' target='_blank'>https://radials.io/api</a>

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncentral

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the EndpointApplicationResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EndpointApplicationResponse{}

// EndpointApplicationResponse Response model for endpoint application
type EndpointApplicationResponse struct {
	// The unique identifier for the endpoint application
	EndpointApplicationId *int32 `json:"endpointApplicationId,omitempty"`
	// The date the endpoint application was created
	DateCreated *time.Time `json:"dateCreated,omitempty"`
	// The date the endpoint application was last modified
	DateModified *time.Time `json:"dateModified,omitempty"`
	// The company ID for tenant isolation
	CompanyId int32 `json:"companyId"`
	// The company endpoint ID
	EndpointId int32 `json:"endpointId"`
	// The name of the application
	Name NullableString `json:"name,omitempty"`
	// The publisher of the application
	Publisher string `json:"publisher"`
	// The readme information
	Readme NullableString `json:"readme,omitempty"`
	// The help URL
	HelpURL NullableString `json:"helpURL,omitempty"`
	// The help phone number
	HelpPhone NullableString `json:"helpPhone,omitempty"`
	// The about URL
	AboutURL NullableString `json:"aboutURL,omitempty"`
	// The update URL
	UpdateURL NullableString `json:"updateURL,omitempty"`
	// Comments about the application
	Comments NullableString `json:"comments,omitempty"`
	// The category of the application
	Category NullableString `json:"category,omitempty"`
	// Whether the application is cloud storage
	IsCloudStorage *bool                 `json:"isCloudStorage,omitempty"`
	PlatformType   *EndpointPlatformType `json:"platformType,omitempty"`
	// The estimated size of the application
	EstimatedSize *int32 `json:"estimatedSize,omitempty"`
	// The install path of the application
	InstallPath NullableString `json:"installPath,omitempty"`
	// The uninstall path of the application
	UninstallPath NullableString `json:"uninstallPath,omitempty"`
	// The modify path of the application
	ModifyPath NullableString `json:"modifyPath,omitempty"`
	// The install date of the application
	InstallDate NullableTime `json:"installDate,omitempty"`
	// The display version of the application
	Display NullableString `json:"display,omitempty"`
	// The major version number
	Major *int32 `json:"major,omitempty"`
	// The minor version number
	Minor *int32 `json:"minor,omitempty"`
	// The version number
	Version *int32 `json:"version,omitempty"`
}

type _EndpointApplicationResponse EndpointApplicationResponse

// NewEndpointApplicationResponse instantiates a new EndpointApplicationResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEndpointApplicationResponse(companyId int32, endpointId int32, publisher string) *EndpointApplicationResponse {
	this := EndpointApplicationResponse{}
	this.CompanyId = companyId
	this.EndpointId = endpointId
	this.Publisher = publisher
	return &this
}

// NewEndpointApplicationResponseWithDefaults instantiates a new EndpointApplicationResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEndpointApplicationResponseWithDefaults() *EndpointApplicationResponse {
	this := EndpointApplicationResponse{}
	return &this
}

// GetEndpointApplicationId returns the EndpointApplicationId field value if set, zero value otherwise.
func (o *EndpointApplicationResponse) GetEndpointApplicationId() int32 {
	if o == nil || IsNil(o.EndpointApplicationId) {
		var ret int32
		return ret
	}
	return *o.EndpointApplicationId
}

// GetEndpointApplicationIdOk returns a tuple with the EndpointApplicationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EndpointApplicationResponse) GetEndpointApplicationIdOk() (*int32, bool) {
	if o == nil || IsNil(o.EndpointApplicationId) {
		return nil, false
	}
	return o.EndpointApplicationId, true
}

// HasEndpointApplicationId returns a boolean if a field has been set.
func (o *EndpointApplicationResponse) HasEndpointApplicationId() bool {
	if o != nil && !IsNil(o.EndpointApplicationId) {
		return true
	}

	return false
}

// SetEndpointApplicationId gets a reference to the given int32 and assigns it to the EndpointApplicationId field.
func (o *EndpointApplicationResponse) SetEndpointApplicationId(v int32) {
	o.EndpointApplicationId = &v
}

// GetDateCreated returns the DateCreated field value if set, zero value otherwise.
func (o *EndpointApplicationResponse) GetDateCreated() time.Time {
	if o == nil || IsNil(o.DateCreated) {
		var ret time.Time
		return ret
	}
	return *o.DateCreated
}

// GetDateCreatedOk returns a tuple with the DateCreated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EndpointApplicationResponse) GetDateCreatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.DateCreated) {
		return nil, false
	}
	return o.DateCreated, true
}

// HasDateCreated returns a boolean if a field has been set.
func (o *EndpointApplicationResponse) HasDateCreated() bool {
	if o != nil && !IsNil(o.DateCreated) {
		return true
	}

	return false
}

// SetDateCreated gets a reference to the given time.Time and assigns it to the DateCreated field.
func (o *EndpointApplicationResponse) SetDateCreated(v time.Time) {
	o.DateCreated = &v
}

// GetDateModified returns the DateModified field value if set, zero value otherwise.
func (o *EndpointApplicationResponse) GetDateModified() time.Time {
	if o == nil || IsNil(o.DateModified) {
		var ret time.Time
		return ret
	}
	return *o.DateModified
}

// GetDateModifiedOk returns a tuple with the DateModified field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EndpointApplicationResponse) GetDateModifiedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.DateModified) {
		return nil, false
	}
	return o.DateModified, true
}

// HasDateModified returns a boolean if a field has been set.
func (o *EndpointApplicationResponse) HasDateModified() bool {
	if o != nil && !IsNil(o.DateModified) {
		return true
	}

	return false
}

// SetDateModified gets a reference to the given time.Time and assigns it to the DateModified field.
func (o *EndpointApplicationResponse) SetDateModified(v time.Time) {
	o.DateModified = &v
}

// GetCompanyId returns the CompanyId field value
func (o *EndpointApplicationResponse) GetCompanyId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CompanyId
}

// GetCompanyIdOk returns a tuple with the CompanyId field value
// and a boolean to check if the value has been set.
func (o *EndpointApplicationResponse) GetCompanyIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CompanyId, true
}

// SetCompanyId sets field value
func (o *EndpointApplicationResponse) SetCompanyId(v int32) {
	o.CompanyId = v
}

// GetEndpointId returns the EndpointId field value
func (o *EndpointApplicationResponse) GetEndpointId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.EndpointId
}

// GetEndpointIdOk returns a tuple with the EndpointId field value
// and a boolean to check if the value has been set.
func (o *EndpointApplicationResponse) GetEndpointIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EndpointId, true
}

// SetEndpointId sets field value
func (o *EndpointApplicationResponse) SetEndpointId(v int32) {
	o.EndpointId = v
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EndpointApplicationResponse) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EndpointApplicationResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *EndpointApplicationResponse) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *EndpointApplicationResponse) SetName(v string) {
	o.Name.Set(&v)
}

// SetNameNil sets the value for Name to be an explicit nil
func (o *EndpointApplicationResponse) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *EndpointApplicationResponse) UnsetName() {
	o.Name.Unset()
}

// GetPublisher returns the Publisher field value
func (o *EndpointApplicationResponse) GetPublisher() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Publisher
}

// GetPublisherOk returns a tuple with the Publisher field value
// and a boolean to check if the value has been set.
func (o *EndpointApplicationResponse) GetPublisherOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Publisher, true
}

// SetPublisher sets field value
func (o *EndpointApplicationResponse) SetPublisher(v string) {
	o.Publisher = v
}

// GetReadme returns the Readme field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EndpointApplicationResponse) GetReadme() string {
	if o == nil || IsNil(o.Readme.Get()) {
		var ret string
		return ret
	}
	return *o.Readme.Get()
}

// GetReadmeOk returns a tuple with the Readme field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EndpointApplicationResponse) GetReadmeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Readme.Get(), o.Readme.IsSet()
}

// HasReadme returns a boolean if a field has been set.
func (o *EndpointApplicationResponse) HasReadme() bool {
	if o != nil && o.Readme.IsSet() {
		return true
	}

	return false
}

// SetReadme gets a reference to the given NullableString and assigns it to the Readme field.
func (o *EndpointApplicationResponse) SetReadme(v string) {
	o.Readme.Set(&v)
}

// SetReadmeNil sets the value for Readme to be an explicit nil
func (o *EndpointApplicationResponse) SetReadmeNil() {
	o.Readme.Set(nil)
}

// UnsetReadme ensures that no value is present for Readme, not even an explicit nil
func (o *EndpointApplicationResponse) UnsetReadme() {
	o.Readme.Unset()
}

// GetHelpURL returns the HelpURL field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EndpointApplicationResponse) GetHelpURL() string {
	if o == nil || IsNil(o.HelpURL.Get()) {
		var ret string
		return ret
	}
	return *o.HelpURL.Get()
}

// GetHelpURLOk returns a tuple with the HelpURL field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EndpointApplicationResponse) GetHelpURLOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.HelpURL.Get(), o.HelpURL.IsSet()
}

// HasHelpURL returns a boolean if a field has been set.
func (o *EndpointApplicationResponse) HasHelpURL() bool {
	if o != nil && o.HelpURL.IsSet() {
		return true
	}

	return false
}

// SetHelpURL gets a reference to the given NullableString and assigns it to the HelpURL field.
func (o *EndpointApplicationResponse) SetHelpURL(v string) {
	o.HelpURL.Set(&v)
}

// SetHelpURLNil sets the value for HelpURL to be an explicit nil
func (o *EndpointApplicationResponse) SetHelpURLNil() {
	o.HelpURL.Set(nil)
}

// UnsetHelpURL ensures that no value is present for HelpURL, not even an explicit nil
func (o *EndpointApplicationResponse) UnsetHelpURL() {
	o.HelpURL.Unset()
}

// GetHelpPhone returns the HelpPhone field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EndpointApplicationResponse) GetHelpPhone() string {
	if o == nil || IsNil(o.HelpPhone.Get()) {
		var ret string
		return ret
	}
	return *o.HelpPhone.Get()
}

// GetHelpPhoneOk returns a tuple with the HelpPhone field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EndpointApplicationResponse) GetHelpPhoneOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.HelpPhone.Get(), o.HelpPhone.IsSet()
}

// HasHelpPhone returns a boolean if a field has been set.
func (o *EndpointApplicationResponse) HasHelpPhone() bool {
	if o != nil && o.HelpPhone.IsSet() {
		return true
	}

	return false
}

// SetHelpPhone gets a reference to the given NullableString and assigns it to the HelpPhone field.
func (o *EndpointApplicationResponse) SetHelpPhone(v string) {
	o.HelpPhone.Set(&v)
}

// SetHelpPhoneNil sets the value for HelpPhone to be an explicit nil
func (o *EndpointApplicationResponse) SetHelpPhoneNil() {
	o.HelpPhone.Set(nil)
}

// UnsetHelpPhone ensures that no value is present for HelpPhone, not even an explicit nil
func (o *EndpointApplicationResponse) UnsetHelpPhone() {
	o.HelpPhone.Unset()
}

// GetAboutURL returns the AboutURL field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EndpointApplicationResponse) GetAboutURL() string {
	if o == nil || IsNil(o.AboutURL.Get()) {
		var ret string
		return ret
	}
	return *o.AboutURL.Get()
}

// GetAboutURLOk returns a tuple with the AboutURL field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EndpointApplicationResponse) GetAboutURLOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AboutURL.Get(), o.AboutURL.IsSet()
}

// HasAboutURL returns a boolean if a field has been set.
func (o *EndpointApplicationResponse) HasAboutURL() bool {
	if o != nil && o.AboutURL.IsSet() {
		return true
	}

	return false
}

// SetAboutURL gets a reference to the given NullableString and assigns it to the AboutURL field.
func (o *EndpointApplicationResponse) SetAboutURL(v string) {
	o.AboutURL.Set(&v)
}

// SetAboutURLNil sets the value for AboutURL to be an explicit nil
func (o *EndpointApplicationResponse) SetAboutURLNil() {
	o.AboutURL.Set(nil)
}

// UnsetAboutURL ensures that no value is present for AboutURL, not even an explicit nil
func (o *EndpointApplicationResponse) UnsetAboutURL() {
	o.AboutURL.Unset()
}

// GetUpdateURL returns the UpdateURL field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EndpointApplicationResponse) GetUpdateURL() string {
	if o == nil || IsNil(o.UpdateURL.Get()) {
		var ret string
		return ret
	}
	return *o.UpdateURL.Get()
}

// GetUpdateURLOk returns a tuple with the UpdateURL field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EndpointApplicationResponse) GetUpdateURLOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.UpdateURL.Get(), o.UpdateURL.IsSet()
}

// HasUpdateURL returns a boolean if a field has been set.
func (o *EndpointApplicationResponse) HasUpdateURL() bool {
	if o != nil && o.UpdateURL.IsSet() {
		return true
	}

	return false
}

// SetUpdateURL gets a reference to the given NullableString and assigns it to the UpdateURL field.
func (o *EndpointApplicationResponse) SetUpdateURL(v string) {
	o.UpdateURL.Set(&v)
}

// SetUpdateURLNil sets the value for UpdateURL to be an explicit nil
func (o *EndpointApplicationResponse) SetUpdateURLNil() {
	o.UpdateURL.Set(nil)
}

// UnsetUpdateURL ensures that no value is present for UpdateURL, not even an explicit nil
func (o *EndpointApplicationResponse) UnsetUpdateURL() {
	o.UpdateURL.Unset()
}

// GetComments returns the Comments field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EndpointApplicationResponse) GetComments() string {
	if o == nil || IsNil(o.Comments.Get()) {
		var ret string
		return ret
	}
	return *o.Comments.Get()
}

// GetCommentsOk returns a tuple with the Comments field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EndpointApplicationResponse) GetCommentsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Comments.Get(), o.Comments.IsSet()
}

// HasComments returns a boolean if a field has been set.
func (o *EndpointApplicationResponse) HasComments() bool {
	if o != nil && o.Comments.IsSet() {
		return true
	}

	return false
}

// SetComments gets a reference to the given NullableString and assigns it to the Comments field.
func (o *EndpointApplicationResponse) SetComments(v string) {
	o.Comments.Set(&v)
}

// SetCommentsNil sets the value for Comments to be an explicit nil
func (o *EndpointApplicationResponse) SetCommentsNil() {
	o.Comments.Set(nil)
}

// UnsetComments ensures that no value is present for Comments, not even an explicit nil
func (o *EndpointApplicationResponse) UnsetComments() {
	o.Comments.Unset()
}

// GetCategory returns the Category field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EndpointApplicationResponse) GetCategory() string {
	if o == nil || IsNil(o.Category.Get()) {
		var ret string
		return ret
	}
	return *o.Category.Get()
}

// GetCategoryOk returns a tuple with the Category field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EndpointApplicationResponse) GetCategoryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Category.Get(), o.Category.IsSet()
}

// HasCategory returns a boolean if a field has been set.
func (o *EndpointApplicationResponse) HasCategory() bool {
	if o != nil && o.Category.IsSet() {
		return true
	}

	return false
}

// SetCategory gets a reference to the given NullableString and assigns it to the Category field.
func (o *EndpointApplicationResponse) SetCategory(v string) {
	o.Category.Set(&v)
}

// SetCategoryNil sets the value for Category to be an explicit nil
func (o *EndpointApplicationResponse) SetCategoryNil() {
	o.Category.Set(nil)
}

// UnsetCategory ensures that no value is present for Category, not even an explicit nil
func (o *EndpointApplicationResponse) UnsetCategory() {
	o.Category.Unset()
}

// GetIsCloudStorage returns the IsCloudStorage field value if set, zero value otherwise.
func (o *EndpointApplicationResponse) GetIsCloudStorage() bool {
	if o == nil || IsNil(o.IsCloudStorage) {
		var ret bool
		return ret
	}
	return *o.IsCloudStorage
}

// GetIsCloudStorageOk returns a tuple with the IsCloudStorage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EndpointApplicationResponse) GetIsCloudStorageOk() (*bool, bool) {
	if o == nil || IsNil(o.IsCloudStorage) {
		return nil, false
	}
	return o.IsCloudStorage, true
}

// HasIsCloudStorage returns a boolean if a field has been set.
func (o *EndpointApplicationResponse) HasIsCloudStorage() bool {
	if o != nil && !IsNil(o.IsCloudStorage) {
		return true
	}

	return false
}

// SetIsCloudStorage gets a reference to the given bool and assigns it to the IsCloudStorage field.
func (o *EndpointApplicationResponse) SetIsCloudStorage(v bool) {
	o.IsCloudStorage = &v
}

// GetPlatformType returns the PlatformType field value if set, zero value otherwise.
func (o *EndpointApplicationResponse) GetPlatformType() EndpointPlatformType {
	if o == nil || IsNil(o.PlatformType) {
		var ret EndpointPlatformType
		return ret
	}
	return *o.PlatformType
}

// GetPlatformTypeOk returns a tuple with the PlatformType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EndpointApplicationResponse) GetPlatformTypeOk() (*EndpointPlatformType, bool) {
	if o == nil || IsNil(o.PlatformType) {
		return nil, false
	}
	return o.PlatformType, true
}

// HasPlatformType returns a boolean if a field has been set.
func (o *EndpointApplicationResponse) HasPlatformType() bool {
	if o != nil && !IsNil(o.PlatformType) {
		return true
	}

	return false
}

// SetPlatformType gets a reference to the given EndpointPlatformType and assigns it to the PlatformType field.
func (o *EndpointApplicationResponse) SetPlatformType(v EndpointPlatformType) {
	o.PlatformType = &v
}

// GetEstimatedSize returns the EstimatedSize field value if set, zero value otherwise.
func (o *EndpointApplicationResponse) GetEstimatedSize() int32 {
	if o == nil || IsNil(o.EstimatedSize) {
		var ret int32
		return ret
	}
	return *o.EstimatedSize
}

// GetEstimatedSizeOk returns a tuple with the EstimatedSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EndpointApplicationResponse) GetEstimatedSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.EstimatedSize) {
		return nil, false
	}
	return o.EstimatedSize, true
}

// HasEstimatedSize returns a boolean if a field has been set.
func (o *EndpointApplicationResponse) HasEstimatedSize() bool {
	if o != nil && !IsNil(o.EstimatedSize) {
		return true
	}

	return false
}

// SetEstimatedSize gets a reference to the given int32 and assigns it to the EstimatedSize field.
func (o *EndpointApplicationResponse) SetEstimatedSize(v int32) {
	o.EstimatedSize = &v
}

// GetInstallPath returns the InstallPath field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EndpointApplicationResponse) GetInstallPath() string {
	if o == nil || IsNil(o.InstallPath.Get()) {
		var ret string
		return ret
	}
	return *o.InstallPath.Get()
}

// GetInstallPathOk returns a tuple with the InstallPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EndpointApplicationResponse) GetInstallPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.InstallPath.Get(), o.InstallPath.IsSet()
}

// HasInstallPath returns a boolean if a field has been set.
func (o *EndpointApplicationResponse) HasInstallPath() bool {
	if o != nil && o.InstallPath.IsSet() {
		return true
	}

	return false
}

// SetInstallPath gets a reference to the given NullableString and assigns it to the InstallPath field.
func (o *EndpointApplicationResponse) SetInstallPath(v string) {
	o.InstallPath.Set(&v)
}

// SetInstallPathNil sets the value for InstallPath to be an explicit nil
func (o *EndpointApplicationResponse) SetInstallPathNil() {
	o.InstallPath.Set(nil)
}

// UnsetInstallPath ensures that no value is present for InstallPath, not even an explicit nil
func (o *EndpointApplicationResponse) UnsetInstallPath() {
	o.InstallPath.Unset()
}

// GetUninstallPath returns the UninstallPath field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EndpointApplicationResponse) GetUninstallPath() string {
	if o == nil || IsNil(o.UninstallPath.Get()) {
		var ret string
		return ret
	}
	return *o.UninstallPath.Get()
}

// GetUninstallPathOk returns a tuple with the UninstallPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EndpointApplicationResponse) GetUninstallPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.UninstallPath.Get(), o.UninstallPath.IsSet()
}

// HasUninstallPath returns a boolean if a field has been set.
func (o *EndpointApplicationResponse) HasUninstallPath() bool {
	if o != nil && o.UninstallPath.IsSet() {
		return true
	}

	return false
}

// SetUninstallPath gets a reference to the given NullableString and assigns it to the UninstallPath field.
func (o *EndpointApplicationResponse) SetUninstallPath(v string) {
	o.UninstallPath.Set(&v)
}

// SetUninstallPathNil sets the value for UninstallPath to be an explicit nil
func (o *EndpointApplicationResponse) SetUninstallPathNil() {
	o.UninstallPath.Set(nil)
}

// UnsetUninstallPath ensures that no value is present for UninstallPath, not even an explicit nil
func (o *EndpointApplicationResponse) UnsetUninstallPath() {
	o.UninstallPath.Unset()
}

// GetModifyPath returns the ModifyPath field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EndpointApplicationResponse) GetModifyPath() string {
	if o == nil || IsNil(o.ModifyPath.Get()) {
		var ret string
		return ret
	}
	return *o.ModifyPath.Get()
}

// GetModifyPathOk returns a tuple with the ModifyPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EndpointApplicationResponse) GetModifyPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ModifyPath.Get(), o.ModifyPath.IsSet()
}

// HasModifyPath returns a boolean if a field has been set.
func (o *EndpointApplicationResponse) HasModifyPath() bool {
	if o != nil && o.ModifyPath.IsSet() {
		return true
	}

	return false
}

// SetModifyPath gets a reference to the given NullableString and assigns it to the ModifyPath field.
func (o *EndpointApplicationResponse) SetModifyPath(v string) {
	o.ModifyPath.Set(&v)
}

// SetModifyPathNil sets the value for ModifyPath to be an explicit nil
func (o *EndpointApplicationResponse) SetModifyPathNil() {
	o.ModifyPath.Set(nil)
}

// UnsetModifyPath ensures that no value is present for ModifyPath, not even an explicit nil
func (o *EndpointApplicationResponse) UnsetModifyPath() {
	o.ModifyPath.Unset()
}

// GetInstallDate returns the InstallDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EndpointApplicationResponse) GetInstallDate() time.Time {
	if o == nil || IsNil(o.InstallDate.Get()) {
		var ret time.Time
		return ret
	}
	return *o.InstallDate.Get()
}

// GetInstallDateOk returns a tuple with the InstallDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EndpointApplicationResponse) GetInstallDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.InstallDate.Get(), o.InstallDate.IsSet()
}

// HasInstallDate returns a boolean if a field has been set.
func (o *EndpointApplicationResponse) HasInstallDate() bool {
	if o != nil && o.InstallDate.IsSet() {
		return true
	}

	return false
}

// SetInstallDate gets a reference to the given NullableTime and assigns it to the InstallDate field.
func (o *EndpointApplicationResponse) SetInstallDate(v time.Time) {
	o.InstallDate.Set(&v)
}

// SetInstallDateNil sets the value for InstallDate to be an explicit nil
func (o *EndpointApplicationResponse) SetInstallDateNil() {
	o.InstallDate.Set(nil)
}

// UnsetInstallDate ensures that no value is present for InstallDate, not even an explicit nil
func (o *EndpointApplicationResponse) UnsetInstallDate() {
	o.InstallDate.Unset()
}

// GetDisplay returns the Display field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EndpointApplicationResponse) GetDisplay() string {
	if o == nil || IsNil(o.Display.Get()) {
		var ret string
		return ret
	}
	return *o.Display.Get()
}

// GetDisplayOk returns a tuple with the Display field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EndpointApplicationResponse) GetDisplayOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Display.Get(), o.Display.IsSet()
}

// HasDisplay returns a boolean if a field has been set.
func (o *EndpointApplicationResponse) HasDisplay() bool {
	if o != nil && o.Display.IsSet() {
		return true
	}

	return false
}

// SetDisplay gets a reference to the given NullableString and assigns it to the Display field.
func (o *EndpointApplicationResponse) SetDisplay(v string) {
	o.Display.Set(&v)
}

// SetDisplayNil sets the value for Display to be an explicit nil
func (o *EndpointApplicationResponse) SetDisplayNil() {
	o.Display.Set(nil)
}

// UnsetDisplay ensures that no value is present for Display, not even an explicit nil
func (o *EndpointApplicationResponse) UnsetDisplay() {
	o.Display.Unset()
}

// GetMajor returns the Major field value if set, zero value otherwise.
func (o *EndpointApplicationResponse) GetMajor() int32 {
	if o == nil || IsNil(o.Major) {
		var ret int32
		return ret
	}
	return *o.Major
}

// GetMajorOk returns a tuple with the Major field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EndpointApplicationResponse) GetMajorOk() (*int32, bool) {
	if o == nil || IsNil(o.Major) {
		return nil, false
	}
	return o.Major, true
}

// HasMajor returns a boolean if a field has been set.
func (o *EndpointApplicationResponse) HasMajor() bool {
	if o != nil && !IsNil(o.Major) {
		return true
	}

	return false
}

// SetMajor gets a reference to the given int32 and assigns it to the Major field.
func (o *EndpointApplicationResponse) SetMajor(v int32) {
	o.Major = &v
}

// GetMinor returns the Minor field value if set, zero value otherwise.
func (o *EndpointApplicationResponse) GetMinor() int32 {
	if o == nil || IsNil(o.Minor) {
		var ret int32
		return ret
	}
	return *o.Minor
}

// GetMinorOk returns a tuple with the Minor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EndpointApplicationResponse) GetMinorOk() (*int32, bool) {
	if o == nil || IsNil(o.Minor) {
		return nil, false
	}
	return o.Minor, true
}

// HasMinor returns a boolean if a field has been set.
func (o *EndpointApplicationResponse) HasMinor() bool {
	if o != nil && !IsNil(o.Minor) {
		return true
	}

	return false
}

// SetMinor gets a reference to the given int32 and assigns it to the Minor field.
func (o *EndpointApplicationResponse) SetMinor(v int32) {
	o.Minor = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *EndpointApplicationResponse) GetVersion() int32 {
	if o == nil || IsNil(o.Version) {
		var ret int32
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EndpointApplicationResponse) GetVersionOk() (*int32, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *EndpointApplicationResponse) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given int32 and assigns it to the Version field.
func (o *EndpointApplicationResponse) SetVersion(v int32) {
	o.Version = &v
}

func (o EndpointApplicationResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EndpointApplicationResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EndpointApplicationId) {
		toSerialize["endpointApplicationId"] = o.EndpointApplicationId
	}
	if !IsNil(o.DateCreated) {
		toSerialize["dateCreated"] = o.DateCreated
	}
	if !IsNil(o.DateModified) {
		toSerialize["dateModified"] = o.DateModified
	}
	toSerialize["companyId"] = o.CompanyId
	toSerialize["endpointId"] = o.EndpointId
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	toSerialize["publisher"] = o.Publisher
	if o.Readme.IsSet() {
		toSerialize["readme"] = o.Readme.Get()
	}
	if o.HelpURL.IsSet() {
		toSerialize["helpURL"] = o.HelpURL.Get()
	}
	if o.HelpPhone.IsSet() {
		toSerialize["helpPhone"] = o.HelpPhone.Get()
	}
	if o.AboutURL.IsSet() {
		toSerialize["aboutURL"] = o.AboutURL.Get()
	}
	if o.UpdateURL.IsSet() {
		toSerialize["updateURL"] = o.UpdateURL.Get()
	}
	if o.Comments.IsSet() {
		toSerialize["comments"] = o.Comments.Get()
	}
	if o.Category.IsSet() {
		toSerialize["category"] = o.Category.Get()
	}
	if !IsNil(o.IsCloudStorage) {
		toSerialize["isCloudStorage"] = o.IsCloudStorage
	}
	if !IsNil(o.PlatformType) {
		toSerialize["platformType"] = o.PlatformType
	}
	if !IsNil(o.EstimatedSize) {
		toSerialize["estimatedSize"] = o.EstimatedSize
	}
	if o.InstallPath.IsSet() {
		toSerialize["installPath"] = o.InstallPath.Get()
	}
	if o.UninstallPath.IsSet() {
		toSerialize["uninstallPath"] = o.UninstallPath.Get()
	}
	if o.ModifyPath.IsSet() {
		toSerialize["modifyPath"] = o.ModifyPath.Get()
	}
	if o.InstallDate.IsSet() {
		toSerialize["installDate"] = o.InstallDate.Get()
	}
	if o.Display.IsSet() {
		toSerialize["display"] = o.Display.Get()
	}
	if !IsNil(o.Major) {
		toSerialize["major"] = o.Major
	}
	if !IsNil(o.Minor) {
		toSerialize["minor"] = o.Minor
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	return toSerialize, nil
}

func (o *EndpointApplicationResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"companyId",
		"endpointId",
		"publisher",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEndpointApplicationResponse := _EndpointApplicationResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEndpointApplicationResponse)

	if err != nil {
		return err
	}

	*o = EndpointApplicationResponse(varEndpointApplicationResponse)

	return err
}

type NullableEndpointApplicationResponse struct {
	value *EndpointApplicationResponse
	isSet bool
}

func (v NullableEndpointApplicationResponse) Get() *EndpointApplicationResponse {
	return v.value
}

func (v *NullableEndpointApplicationResponse) Set(val *EndpointApplicationResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableEndpointApplicationResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableEndpointApplicationResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEndpointApplicationResponse(val *EndpointApplicationResponse) *NullableEndpointApplicationResponse {
	return &NullableEndpointApplicationResponse{value: val, isSet: true}
}

func (v NullableEndpointApplicationResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEndpointApplicationResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
