/*
CloudRadial

The CloudRadial API is currently in development. For more information visit <a href='https://radials.io/api' target='_blank'>https://radials.io/api</a>

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncentral

import (
	"encoding/json"
	"time"
)

// checks if the CourseCompletionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CourseCompletionRequest{}

// CourseCompletionRequest struct for CourseCompletionRequest
type CourseCompletionRequest struct {
	// Optional score achieved in the course (percentage)
	Score NullableInt32 `json:"score,omitempty"`
	// Optional comment or feedback about the course
	Comment        NullableString `json:"comment,omitempty"`
	CompletionDate NullableTime   `json:"completionDate,omitempty"`
}

// NewCourseCompletionRequest instantiates a new CourseCompletionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCourseCompletionRequest() *CourseCompletionRequest {
	this := CourseCompletionRequest{}
	return &this
}

// NewCourseCompletionRequestWithDefaults instantiates a new CourseCompletionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCourseCompletionRequestWithDefaults() *CourseCompletionRequest {
	this := CourseCompletionRequest{}
	return &this
}

// GetScore returns the Score field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CourseCompletionRequest) GetScore() int32 {
	if o == nil || IsNil(o.Score.Get()) {
		var ret int32
		return ret
	}
	return *o.Score.Get()
}

// GetScoreOk returns a tuple with the Score field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CourseCompletionRequest) GetScoreOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Score.Get(), o.Score.IsSet()
}

// HasScore returns a boolean if a field has been set.
func (o *CourseCompletionRequest) HasScore() bool {
	if o != nil && o.Score.IsSet() {
		return true
	}

	return false
}

// SetScore gets a reference to the given NullableInt32 and assigns it to the Score field.
func (o *CourseCompletionRequest) SetScore(v int32) {
	o.Score.Set(&v)
}

// SetScoreNil sets the value for Score to be an explicit nil
func (o *CourseCompletionRequest) SetScoreNil() {
	o.Score.Set(nil)
}

// UnsetScore ensures that no value is present for Score, not even an explicit nil
func (o *CourseCompletionRequest) UnsetScore() {
	o.Score.Unset()
}

// GetComment returns the Comment field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CourseCompletionRequest) GetComment() string {
	if o == nil || IsNil(o.Comment.Get()) {
		var ret string
		return ret
	}
	return *o.Comment.Get()
}

// GetCommentOk returns a tuple with the Comment field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CourseCompletionRequest) GetCommentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Comment.Get(), o.Comment.IsSet()
}

// HasComment returns a boolean if a field has been set.
func (o *CourseCompletionRequest) HasComment() bool {
	if o != nil && o.Comment.IsSet() {
		return true
	}

	return false
}

// SetComment gets a reference to the given NullableString and assigns it to the Comment field.
func (o *CourseCompletionRequest) SetComment(v string) {
	o.Comment.Set(&v)
}

// SetCommentNil sets the value for Comment to be an explicit nil
func (o *CourseCompletionRequest) SetCommentNil() {
	o.Comment.Set(nil)
}

// UnsetComment ensures that no value is present for Comment, not even an explicit nil
func (o *CourseCompletionRequest) UnsetComment() {
	o.Comment.Unset()
}

// GetCompletionDate returns the CompletionDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CourseCompletionRequest) GetCompletionDate() time.Time {
	if o == nil || IsNil(o.CompletionDate.Get()) {
		var ret time.Time
		return ret
	}
	return *o.CompletionDate.Get()
}

// GetCompletionDateOk returns a tuple with the CompletionDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CourseCompletionRequest) GetCompletionDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.CompletionDate.Get(), o.CompletionDate.IsSet()
}

// HasCompletionDate returns a boolean if a field has been set.
func (o *CourseCompletionRequest) HasCompletionDate() bool {
	if o != nil && o.CompletionDate.IsSet() {
		return true
	}

	return false
}

// SetCompletionDate gets a reference to the given NullableTime and assigns it to the CompletionDate field.
func (o *CourseCompletionRequest) SetCompletionDate(v time.Time) {
	o.CompletionDate.Set(&v)
}

// SetCompletionDateNil sets the value for CompletionDate to be an explicit nil
func (o *CourseCompletionRequest) SetCompletionDateNil() {
	o.CompletionDate.Set(nil)
}

// UnsetCompletionDate ensures that no value is present for CompletionDate, not even an explicit nil
func (o *CourseCompletionRequest) UnsetCompletionDate() {
	o.CompletionDate.Unset()
}

func (o CourseCompletionRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CourseCompletionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Score.IsSet() {
		toSerialize["score"] = o.Score.Get()
	}
	if o.Comment.IsSet() {
		toSerialize["comment"] = o.Comment.Get()
	}
	if o.CompletionDate.IsSet() {
		toSerialize["completionDate"] = o.CompletionDate.Get()
	}
	return toSerialize, nil
}

type NullableCourseCompletionRequest struct {
	value *CourseCompletionRequest
	isSet bool
}

func (v NullableCourseCompletionRequest) Get() *CourseCompletionRequest {
	return v.value
}

func (v *NullableCourseCompletionRequest) Set(val *CourseCompletionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCourseCompletionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCourseCompletionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCourseCompletionRequest(val *CourseCompletionRequest) *NullableCourseCompletionRequest {
	return &NullableCourseCompletionRequest{value: val, isSet: true}
}

func (v NullableCourseCompletionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCourseCompletionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
