/*
CloudRadial

The CloudRadial API is currently in development. For more information visit <a href='https://radials.io/api' target='_blank'>https://radials.io/api</a>

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncentral

import (
	"encoding/json"
)

// checks if the FeedbackResponseStandardAPIResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FeedbackResponseStandardAPIResponse{}

// FeedbackResponseStandardAPIResponse Generic API response. All API endpoints should return messages in this format.
type FeedbackResponseStandardAPIResponse struct {
	Data *FeedbackResponse `json:"data,omitempty"`
	// The status of the API call if not success
	Success *bool `json:"success,omitempty"`
	// Any relevant messages for the consumer
	Message NullableString `json:"message,omitempty"`
}

// NewFeedbackResponseStandardAPIResponse instantiates a new FeedbackResponseStandardAPIResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFeedbackResponseStandardAPIResponse() *FeedbackResponseStandardAPIResponse {
	this := FeedbackResponseStandardAPIResponse{}
	return &this
}

// NewFeedbackResponseStandardAPIResponseWithDefaults instantiates a new FeedbackResponseStandardAPIResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFeedbackResponseStandardAPIResponseWithDefaults() *FeedbackResponseStandardAPIResponse {
	this := FeedbackResponseStandardAPIResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *FeedbackResponseStandardAPIResponse) GetData() FeedbackResponse {
	if o == nil || IsNil(o.Data) {
		var ret FeedbackResponse
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeedbackResponseStandardAPIResponse) GetDataOk() (*FeedbackResponse, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *FeedbackResponseStandardAPIResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given FeedbackResponse and assigns it to the Data field.
func (o *FeedbackResponseStandardAPIResponse) SetData(v FeedbackResponse) {
	o.Data = &v
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *FeedbackResponseStandardAPIResponse) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeedbackResponseStandardAPIResponse) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *FeedbackResponseStandardAPIResponse) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *FeedbackResponseStandardAPIResponse) SetSuccess(v bool) {
	o.Success = &v
}

// GetMessage returns the Message field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FeedbackResponseStandardAPIResponse) GetMessage() string {
	if o == nil || IsNil(o.Message.Get()) {
		var ret string
		return ret
	}
	return *o.Message.Get()
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FeedbackResponseStandardAPIResponse) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Message.Get(), o.Message.IsSet()
}

// HasMessage returns a boolean if a field has been set.
func (o *FeedbackResponseStandardAPIResponse) HasMessage() bool {
	if o != nil && o.Message.IsSet() {
		return true
	}

	return false
}

// SetMessage gets a reference to the given NullableString and assigns it to the Message field.
func (o *FeedbackResponseStandardAPIResponse) SetMessage(v string) {
	o.Message.Set(&v)
}

// SetMessageNil sets the value for Message to be an explicit nil
func (o *FeedbackResponseStandardAPIResponse) SetMessageNil() {
	o.Message.Set(nil)
}

// UnsetMessage ensures that no value is present for Message, not even an explicit nil
func (o *FeedbackResponseStandardAPIResponse) UnsetMessage() {
	o.Message.Unset()
}

func (o FeedbackResponseStandardAPIResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FeedbackResponseStandardAPIResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if o.Message.IsSet() {
		toSerialize["message"] = o.Message.Get()
	}
	return toSerialize, nil
}

type NullableFeedbackResponseStandardAPIResponse struct {
	value *FeedbackResponseStandardAPIResponse
	isSet bool
}

func (v NullableFeedbackResponseStandardAPIResponse) Get() *FeedbackResponseStandardAPIResponse {
	return v.value
}

func (v *NullableFeedbackResponseStandardAPIResponse) Set(val *FeedbackResponseStandardAPIResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableFeedbackResponseStandardAPIResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableFeedbackResponseStandardAPIResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFeedbackResponseStandardAPIResponse(val *FeedbackResponseStandardAPIResponse) *NullableFeedbackResponseStandardAPIResponse {
	return &NullableFeedbackResponseStandardAPIResponse{value: val, isSet: true}
}

func (v NullableFeedbackResponseStandardAPIResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFeedbackResponseStandardAPIResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
