/*
CloudRadial

The CloudRadial API is currently in development. For more information visit <a href='https://radials.io/api' target='_blank'>https://radials.io/api</a>

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncentral

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the CompanyDomainRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CompanyDomainRequest{}

// CompanyDomainRequest struct for CompanyDomainRequest
type CompanyDomainRequest struct {
	CompanyId      int32          `json:"companyId"`
	Name           string         `json:"name"`
	Description    NullableString `json:"description,omitempty"`
	Registrar      NullableString `json:"registrar,omitempty"`
	HostingCompany NullableString `json:"hostingCompany,omitempty"`
	ContactName    NullableString `json:"contactName,omitempty"`
	ContactEmail   NullableString `json:"contactEmail,omitempty"`
	ContactPhone   NullableString `json:"contactPhone,omitempty"`
	DateExpires    *time.Time     `json:"dateExpires,omitempty"`
	IsVerified     *bool          `json:"isVerified,omitempty"`
	IsOffice365    *bool          `json:"isOffice365,omitempty"`
	IsDefault      *bool          `json:"isDefault,omitempty"`
	Source         *DataSource    `json:"source,omitempty"`
}

type _CompanyDomainRequest CompanyDomainRequest

// NewCompanyDomainRequest instantiates a new CompanyDomainRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCompanyDomainRequest(companyId int32, name string) *CompanyDomainRequest {
	this := CompanyDomainRequest{}
	this.CompanyId = companyId
	this.Name = name
	return &this
}

// NewCompanyDomainRequestWithDefaults instantiates a new CompanyDomainRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCompanyDomainRequestWithDefaults() *CompanyDomainRequest {
	this := CompanyDomainRequest{}
	return &this
}

// GetCompanyId returns the CompanyId field value
func (o *CompanyDomainRequest) GetCompanyId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CompanyId
}

// GetCompanyIdOk returns a tuple with the CompanyId field value
// and a boolean to check if the value has been set.
func (o *CompanyDomainRequest) GetCompanyIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CompanyId, true
}

// SetCompanyId sets field value
func (o *CompanyDomainRequest) SetCompanyId(v int32) {
	o.CompanyId = v
}

// GetName returns the Name field value
func (o *CompanyDomainRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CompanyDomainRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CompanyDomainRequest) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CompanyDomainRequest) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CompanyDomainRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *CompanyDomainRequest) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *CompanyDomainRequest) SetDescription(v string) {
	o.Description.Set(&v)
}

// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *CompanyDomainRequest) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *CompanyDomainRequest) UnsetDescription() {
	o.Description.Unset()
}

// GetRegistrar returns the Registrar field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CompanyDomainRequest) GetRegistrar() string {
	if o == nil || IsNil(o.Registrar.Get()) {
		var ret string
		return ret
	}
	return *o.Registrar.Get()
}

// GetRegistrarOk returns a tuple with the Registrar field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CompanyDomainRequest) GetRegistrarOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Registrar.Get(), o.Registrar.IsSet()
}

// HasRegistrar returns a boolean if a field has been set.
func (o *CompanyDomainRequest) HasRegistrar() bool {
	if o != nil && o.Registrar.IsSet() {
		return true
	}

	return false
}

// SetRegistrar gets a reference to the given NullableString and assigns it to the Registrar field.
func (o *CompanyDomainRequest) SetRegistrar(v string) {
	o.Registrar.Set(&v)
}

// SetRegistrarNil sets the value for Registrar to be an explicit nil
func (o *CompanyDomainRequest) SetRegistrarNil() {
	o.Registrar.Set(nil)
}

// UnsetRegistrar ensures that no value is present for Registrar, not even an explicit nil
func (o *CompanyDomainRequest) UnsetRegistrar() {
	o.Registrar.Unset()
}

// GetHostingCompany returns the HostingCompany field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CompanyDomainRequest) GetHostingCompany() string {
	if o == nil || IsNil(o.HostingCompany.Get()) {
		var ret string
		return ret
	}
	return *o.HostingCompany.Get()
}

// GetHostingCompanyOk returns a tuple with the HostingCompany field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CompanyDomainRequest) GetHostingCompanyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.HostingCompany.Get(), o.HostingCompany.IsSet()
}

// HasHostingCompany returns a boolean if a field has been set.
func (o *CompanyDomainRequest) HasHostingCompany() bool {
	if o != nil && o.HostingCompany.IsSet() {
		return true
	}

	return false
}

// SetHostingCompany gets a reference to the given NullableString and assigns it to the HostingCompany field.
func (o *CompanyDomainRequest) SetHostingCompany(v string) {
	o.HostingCompany.Set(&v)
}

// SetHostingCompanyNil sets the value for HostingCompany to be an explicit nil
func (o *CompanyDomainRequest) SetHostingCompanyNil() {
	o.HostingCompany.Set(nil)
}

// UnsetHostingCompany ensures that no value is present for HostingCompany, not even an explicit nil
func (o *CompanyDomainRequest) UnsetHostingCompany() {
	o.HostingCompany.Unset()
}

// GetContactName returns the ContactName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CompanyDomainRequest) GetContactName() string {
	if o == nil || IsNil(o.ContactName.Get()) {
		var ret string
		return ret
	}
	return *o.ContactName.Get()
}

// GetContactNameOk returns a tuple with the ContactName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CompanyDomainRequest) GetContactNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ContactName.Get(), o.ContactName.IsSet()
}

// HasContactName returns a boolean if a field has been set.
func (o *CompanyDomainRequest) HasContactName() bool {
	if o != nil && o.ContactName.IsSet() {
		return true
	}

	return false
}

// SetContactName gets a reference to the given NullableString and assigns it to the ContactName field.
func (o *CompanyDomainRequest) SetContactName(v string) {
	o.ContactName.Set(&v)
}

// SetContactNameNil sets the value for ContactName to be an explicit nil
func (o *CompanyDomainRequest) SetContactNameNil() {
	o.ContactName.Set(nil)
}

// UnsetContactName ensures that no value is present for ContactName, not even an explicit nil
func (o *CompanyDomainRequest) UnsetContactName() {
	o.ContactName.Unset()
}

// GetContactEmail returns the ContactEmail field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CompanyDomainRequest) GetContactEmail() string {
	if o == nil || IsNil(o.ContactEmail.Get()) {
		var ret string
		return ret
	}
	return *o.ContactEmail.Get()
}

// GetContactEmailOk returns a tuple with the ContactEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CompanyDomainRequest) GetContactEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ContactEmail.Get(), o.ContactEmail.IsSet()
}

// HasContactEmail returns a boolean if a field has been set.
func (o *CompanyDomainRequest) HasContactEmail() bool {
	if o != nil && o.ContactEmail.IsSet() {
		return true
	}

	return false
}

// SetContactEmail gets a reference to the given NullableString and assigns it to the ContactEmail field.
func (o *CompanyDomainRequest) SetContactEmail(v string) {
	o.ContactEmail.Set(&v)
}

// SetContactEmailNil sets the value for ContactEmail to be an explicit nil
func (o *CompanyDomainRequest) SetContactEmailNil() {
	o.ContactEmail.Set(nil)
}

// UnsetContactEmail ensures that no value is present for ContactEmail, not even an explicit nil
func (o *CompanyDomainRequest) UnsetContactEmail() {
	o.ContactEmail.Unset()
}

// GetContactPhone returns the ContactPhone field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CompanyDomainRequest) GetContactPhone() string {
	if o == nil || IsNil(o.ContactPhone.Get()) {
		var ret string
		return ret
	}
	return *o.ContactPhone.Get()
}

// GetContactPhoneOk returns a tuple with the ContactPhone field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CompanyDomainRequest) GetContactPhoneOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ContactPhone.Get(), o.ContactPhone.IsSet()
}

// HasContactPhone returns a boolean if a field has been set.
func (o *CompanyDomainRequest) HasContactPhone() bool {
	if o != nil && o.ContactPhone.IsSet() {
		return true
	}

	return false
}

// SetContactPhone gets a reference to the given NullableString and assigns it to the ContactPhone field.
func (o *CompanyDomainRequest) SetContactPhone(v string) {
	o.ContactPhone.Set(&v)
}

// SetContactPhoneNil sets the value for ContactPhone to be an explicit nil
func (o *CompanyDomainRequest) SetContactPhoneNil() {
	o.ContactPhone.Set(nil)
}

// UnsetContactPhone ensures that no value is present for ContactPhone, not even an explicit nil
func (o *CompanyDomainRequest) UnsetContactPhone() {
	o.ContactPhone.Unset()
}

// GetDateExpires returns the DateExpires field value if set, zero value otherwise.
func (o *CompanyDomainRequest) GetDateExpires() time.Time {
	if o == nil || IsNil(o.DateExpires) {
		var ret time.Time
		return ret
	}
	return *o.DateExpires
}

// GetDateExpiresOk returns a tuple with the DateExpires field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyDomainRequest) GetDateExpiresOk() (*time.Time, bool) {
	if o == nil || IsNil(o.DateExpires) {
		return nil, false
	}
	return o.DateExpires, true
}

// HasDateExpires returns a boolean if a field has been set.
func (o *CompanyDomainRequest) HasDateExpires() bool {
	if o != nil && !IsNil(o.DateExpires) {
		return true
	}

	return false
}

// SetDateExpires gets a reference to the given time.Time and assigns it to the DateExpires field.
func (o *CompanyDomainRequest) SetDateExpires(v time.Time) {
	o.DateExpires = &v
}

// GetIsVerified returns the IsVerified field value if set, zero value otherwise.
func (o *CompanyDomainRequest) GetIsVerified() bool {
	if o == nil || IsNil(o.IsVerified) {
		var ret bool
		return ret
	}
	return *o.IsVerified
}

// GetIsVerifiedOk returns a tuple with the IsVerified field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyDomainRequest) GetIsVerifiedOk() (*bool, bool) {
	if o == nil || IsNil(o.IsVerified) {
		return nil, false
	}
	return o.IsVerified, true
}

// HasIsVerified returns a boolean if a field has been set.
func (o *CompanyDomainRequest) HasIsVerified() bool {
	if o != nil && !IsNil(o.IsVerified) {
		return true
	}

	return false
}

// SetIsVerified gets a reference to the given bool and assigns it to the IsVerified field.
func (o *CompanyDomainRequest) SetIsVerified(v bool) {
	o.IsVerified = &v
}

// GetIsOffice365 returns the IsOffice365 field value if set, zero value otherwise.
func (o *CompanyDomainRequest) GetIsOffice365() bool {
	if o == nil || IsNil(o.IsOffice365) {
		var ret bool
		return ret
	}
	return *o.IsOffice365
}

// GetIsOffice365Ok returns a tuple with the IsOffice365 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyDomainRequest) GetIsOffice365Ok() (*bool, bool) {
	if o == nil || IsNil(o.IsOffice365) {
		return nil, false
	}
	return o.IsOffice365, true
}

// HasIsOffice365 returns a boolean if a field has been set.
func (o *CompanyDomainRequest) HasIsOffice365() bool {
	if o != nil && !IsNil(o.IsOffice365) {
		return true
	}

	return false
}

// SetIsOffice365 gets a reference to the given bool and assigns it to the IsOffice365 field.
func (o *CompanyDomainRequest) SetIsOffice365(v bool) {
	o.IsOffice365 = &v
}

// GetIsDefault returns the IsDefault field value if set, zero value otherwise.
func (o *CompanyDomainRequest) GetIsDefault() bool {
	if o == nil || IsNil(o.IsDefault) {
		var ret bool
		return ret
	}
	return *o.IsDefault
}

// GetIsDefaultOk returns a tuple with the IsDefault field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyDomainRequest) GetIsDefaultOk() (*bool, bool) {
	if o == nil || IsNil(o.IsDefault) {
		return nil, false
	}
	return o.IsDefault, true
}

// HasIsDefault returns a boolean if a field has been set.
func (o *CompanyDomainRequest) HasIsDefault() bool {
	if o != nil && !IsNil(o.IsDefault) {
		return true
	}

	return false
}

// SetIsDefault gets a reference to the given bool and assigns it to the IsDefault field.
func (o *CompanyDomainRequest) SetIsDefault(v bool) {
	o.IsDefault = &v
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *CompanyDomainRequest) GetSource() DataSource {
	if o == nil || IsNil(o.Source) {
		var ret DataSource
		return ret
	}
	return *o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompanyDomainRequest) GetSourceOk() (*DataSource, bool) {
	if o == nil || IsNil(o.Source) {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *CompanyDomainRequest) HasSource() bool {
	if o != nil && !IsNil(o.Source) {
		return true
	}

	return false
}

// SetSource gets a reference to the given DataSource and assigns it to the Source field.
func (o *CompanyDomainRequest) SetSource(v DataSource) {
	o.Source = &v
}

func (o CompanyDomainRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CompanyDomainRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["companyId"] = o.CompanyId
	toSerialize["name"] = o.Name
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if o.Registrar.IsSet() {
		toSerialize["registrar"] = o.Registrar.Get()
	}
	if o.HostingCompany.IsSet() {
		toSerialize["hostingCompany"] = o.HostingCompany.Get()
	}
	if o.ContactName.IsSet() {
		toSerialize["contactName"] = o.ContactName.Get()
	}
	if o.ContactEmail.IsSet() {
		toSerialize["contactEmail"] = o.ContactEmail.Get()
	}
	if o.ContactPhone.IsSet() {
		toSerialize["contactPhone"] = o.ContactPhone.Get()
	}
	if !IsNil(o.DateExpires) {
		toSerialize["dateExpires"] = o.DateExpires
	}
	if !IsNil(o.IsVerified) {
		toSerialize["isVerified"] = o.IsVerified
	}
	if !IsNil(o.IsOffice365) {
		toSerialize["isOffice365"] = o.IsOffice365
	}
	if !IsNil(o.IsDefault) {
		toSerialize["isDefault"] = o.IsDefault
	}
	if !IsNil(o.Source) {
		toSerialize["source"] = o.Source
	}
	return toSerialize, nil
}

func (o *CompanyDomainRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"companyId",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCompanyDomainRequest := _CompanyDomainRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCompanyDomainRequest)

	if err != nil {
		return err
	}

	*o = CompanyDomainRequest(varCompanyDomainRequest)

	return err
}

type NullableCompanyDomainRequest struct {
	value *CompanyDomainRequest
	isSet bool
}

func (v NullableCompanyDomainRequest) Get() *CompanyDomainRequest {
	return v.value
}

func (v *NullableCompanyDomainRequest) Set(val *CompanyDomainRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCompanyDomainRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCompanyDomainRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCompanyDomainRequest(val *CompanyDomainRequest) *NullableCompanyDomainRequest {
	return &NullableCompanyDomainRequest{value: val, isSet: true}
}

func (v NullableCompanyDomainRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCompanyDomainRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
