/*
CloudRadial

The CloudRadial API is currently in development. For more information visit <a href='https://radials.io/api' target='_blank'>https://radials.io/api</a>

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloudradial

import (
	"encoding/json"
)

// checks if the FlexibleAssetTypeRelationshipsCreateDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FlexibleAssetTypeRelationshipsCreateDto{}

// FlexibleAssetTypeRelationshipsCreateDto struct for FlexibleAssetTypeRelationshipsCreateDto
type FlexibleAssetTypeRelationshipsCreateDto struct {
	FlexibleAssetFields *FlexibleAssetTypeRelationshipDataCreateDto `json:"flexible-asset-fields,omitempty"`
}

// NewFlexibleAssetTypeRelationshipsCreateDto instantiates a new FlexibleAssetTypeRelationshipsCreateDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFlexibleAssetTypeRelationshipsCreateDto() *FlexibleAssetTypeRelationshipsCreateDto {
	this := FlexibleAssetTypeRelationshipsCreateDto{}
	return &this
}

// NewFlexibleAssetTypeRelationshipsCreateDtoWithDefaults instantiates a new FlexibleAssetTypeRelationshipsCreateDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFlexibleAssetTypeRelationshipsCreateDtoWithDefaults() *FlexibleAssetTypeRelationshipsCreateDto {
	this := FlexibleAssetTypeRelationshipsCreateDto{}
	return &this
}

// GetFlexibleAssetFields returns the FlexibleAssetFields field value if set, zero value otherwise.
func (o *FlexibleAssetTypeRelationshipsCreateDto) GetFlexibleAssetFields() FlexibleAssetTypeRelationshipDataCreateDto {
	if o == nil || IsNil(o.FlexibleAssetFields) {
		var ret FlexibleAssetTypeRelationshipDataCreateDto
		return ret
	}
	return *o.FlexibleAssetFields
}

// GetFlexibleAssetFieldsOk returns a tuple with the FlexibleAssetFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FlexibleAssetTypeRelationshipsCreateDto) GetFlexibleAssetFieldsOk() (*FlexibleAssetTypeRelationshipDataCreateDto, bool) {
	if o == nil || IsNil(o.FlexibleAssetFields) {
		return nil, false
	}
	return o.FlexibleAssetFields, true
}

// HasFlexibleAssetFields returns a boolean if a field has been set.
func (o *FlexibleAssetTypeRelationshipsCreateDto) HasFlexibleAssetFields() bool {
	if o != nil && !IsNil(o.FlexibleAssetFields) {
		return true
	}

	return false
}

// SetFlexibleAssetFields gets a reference to the given FlexibleAssetTypeRelationshipDataCreateDto and assigns it to the FlexibleAssetFields field.
func (o *FlexibleAssetTypeRelationshipsCreateDto) SetFlexibleAssetFields(v FlexibleAssetTypeRelationshipDataCreateDto) {
	o.FlexibleAssetFields = &v
}

func (o FlexibleAssetTypeRelationshipsCreateDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FlexibleAssetTypeRelationshipsCreateDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FlexibleAssetFields) {
		toSerialize["flexible-asset-fields"] = o.FlexibleAssetFields
	}
	return toSerialize, nil
}

type NullableFlexibleAssetTypeRelationshipsCreateDto struct {
	value *FlexibleAssetTypeRelationshipsCreateDto
	isSet bool
}

func (v NullableFlexibleAssetTypeRelationshipsCreateDto) Get() *FlexibleAssetTypeRelationshipsCreateDto {
	return v.value
}

func (v *NullableFlexibleAssetTypeRelationshipsCreateDto) Set(val *FlexibleAssetTypeRelationshipsCreateDto) {
	v.value = val
	v.isSet = true
}

func (v NullableFlexibleAssetTypeRelationshipsCreateDto) IsSet() bool {
	return v.isSet
}

func (v *NullableFlexibleAssetTypeRelationshipsCreateDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFlexibleAssetTypeRelationshipsCreateDto(val *FlexibleAssetTypeRelationshipsCreateDto) *NullableFlexibleAssetTypeRelationshipsCreateDto {
	return &NullableFlexibleAssetTypeRelationshipsCreateDto{value: val, isSet: true}
}

func (v NullableFlexibleAssetTypeRelationshipsCreateDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFlexibleAssetTypeRelationshipsCreateDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
