/*
CloudRadial

The CloudRadial API is currently in development. For more information visit <a href='https://radials.io/api' target='_blank'>https://radials.io/api</a>

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloudradial

import (
	"encoding/json"
)

// checks if the EndpointCustomPropertyMutationDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EndpointCustomPropertyMutationDto{}

// EndpointCustomPropertyMutationDto struct for EndpointCustomPropertyMutationDto
type EndpointCustomPropertyMutationDto struct {
	Name     NullableString `json:"name,omitempty"`
	Value    NullableString `json:"value,omitempty"`
	DataType NullableString `json:"dataType,omitempty"`
}

// NewEndpointCustomPropertyMutationDto instantiates a new EndpointCustomPropertyMutationDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEndpointCustomPropertyMutationDto() *EndpointCustomPropertyMutationDto {
	this := EndpointCustomPropertyMutationDto{}
	return &this
}

// NewEndpointCustomPropertyMutationDtoWithDefaults instantiates a new EndpointCustomPropertyMutationDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEndpointCustomPropertyMutationDtoWithDefaults() *EndpointCustomPropertyMutationDto {
	this := EndpointCustomPropertyMutationDto{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EndpointCustomPropertyMutationDto) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EndpointCustomPropertyMutationDto) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *EndpointCustomPropertyMutationDto) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *EndpointCustomPropertyMutationDto) SetName(v string) {
	o.Name.Set(&v)
}

// SetNameNil sets the value for Name to be an explicit nil
func (o *EndpointCustomPropertyMutationDto) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *EndpointCustomPropertyMutationDto) UnsetName() {
	o.Name.Unset()
}

// GetValue returns the Value field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EndpointCustomPropertyMutationDto) GetValue() string {
	if o == nil || IsNil(o.Value.Get()) {
		var ret string
		return ret
	}
	return *o.Value.Get()
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EndpointCustomPropertyMutationDto) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Value.Get(), o.Value.IsSet()
}

// HasValue returns a boolean if a field has been set.
func (o *EndpointCustomPropertyMutationDto) HasValue() bool {
	if o != nil && o.Value.IsSet() {
		return true
	}

	return false
}

// SetValue gets a reference to the given NullableString and assigns it to the Value field.
func (o *EndpointCustomPropertyMutationDto) SetValue(v string) {
	o.Value.Set(&v)
}

// SetValueNil sets the value for Value to be an explicit nil
func (o *EndpointCustomPropertyMutationDto) SetValueNil() {
	o.Value.Set(nil)
}

// UnsetValue ensures that no value is present for Value, not even an explicit nil
func (o *EndpointCustomPropertyMutationDto) UnsetValue() {
	o.Value.Unset()
}

// GetDataType returns the DataType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EndpointCustomPropertyMutationDto) GetDataType() string {
	if o == nil || IsNil(o.DataType.Get()) {
		var ret string
		return ret
	}
	return *o.DataType.Get()
}

// GetDataTypeOk returns a tuple with the DataType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EndpointCustomPropertyMutationDto) GetDataTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DataType.Get(), o.DataType.IsSet()
}

// HasDataType returns a boolean if a field has been set.
func (o *EndpointCustomPropertyMutationDto) HasDataType() bool {
	if o != nil && o.DataType.IsSet() {
		return true
	}

	return false
}

// SetDataType gets a reference to the given NullableString and assigns it to the DataType field.
func (o *EndpointCustomPropertyMutationDto) SetDataType(v string) {
	o.DataType.Set(&v)
}

// SetDataTypeNil sets the value for DataType to be an explicit nil
func (o *EndpointCustomPropertyMutationDto) SetDataTypeNil() {
	o.DataType.Set(nil)
}

// UnsetDataType ensures that no value is present for DataType, not even an explicit nil
func (o *EndpointCustomPropertyMutationDto) UnsetDataType() {
	o.DataType.Unset()
}

func (o EndpointCustomPropertyMutationDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EndpointCustomPropertyMutationDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.Value.IsSet() {
		toSerialize["value"] = o.Value.Get()
	}
	if o.DataType.IsSet() {
		toSerialize["dataType"] = o.DataType.Get()
	}
	return toSerialize, nil
}

type NullableEndpointCustomPropertyMutationDto struct {
	value *EndpointCustomPropertyMutationDto
	isSet bool
}

func (v NullableEndpointCustomPropertyMutationDto) Get() *EndpointCustomPropertyMutationDto {
	return v.value
}

func (v *NullableEndpointCustomPropertyMutationDto) Set(val *EndpointCustomPropertyMutationDto) {
	v.value = val
	v.isSet = true
}

func (v NullableEndpointCustomPropertyMutationDto) IsSet() bool {
	return v.isSet
}

func (v *NullableEndpointCustomPropertyMutationDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEndpointCustomPropertyMutationDto(val *EndpointCustomPropertyMutationDto) *NullableEndpointCustomPropertyMutationDto {
	return &NullableEndpointCustomPropertyMutationDto{value: val, isSet: true}
}

func (v NullableEndpointCustomPropertyMutationDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEndpointCustomPropertyMutationDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
