/*
CloudRadial

The CloudRadial API is currently in development. For more information visit <a href='https://radials.io/api' target='_blank'>https://radials.io/api</a>

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncentral

import (
	"encoding/json"
	"fmt"
)

// Windows11Status the model 'Windows11Status'
type Windows11Status int32

// List of Windows11Status
const (
	_1       Windows11Status = 1
	_2       Windows11Status = 2
	_MINUS_2 Windows11Status = -2
	_MINUS_1 Windows11Status = -1
)

// All allowed values of Windows11Status enum
var AllowedWindows11StatusEnumValues = []Windows11Status{
	1,
	2,
	-2,
	-1,
}

func (v *Windows11Status) UnmarshalJSON(src []byte) error {
	var value int32
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := Windows11Status(value)
	for _, existing := range AllowedWindows11StatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid Windows11Status", value)
}

// NewWindows11StatusFromValue returns a pointer to a valid Windows11Status
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewWindows11StatusFromValue(v int32) (*Windows11Status, error) {
	ev := Windows11Status(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for Windows11Status: valid values are %v", v, AllowedWindows11StatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v Windows11Status) IsValid() bool {
	for _, existing := range AllowedWindows11StatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to Windows11Status value
func (v Windows11Status) Ptr() *Windows11Status {
	return &v
}

type NullableWindows11Status struct {
	value *Windows11Status
	isSet bool
}

func (v NullableWindows11Status) Get() *Windows11Status {
	return v.value
}

func (v *NullableWindows11Status) Set(val *Windows11Status) {
	v.value = val
	v.isSet = true
}

func (v NullableWindows11Status) IsSet() bool {
	return v.isSet
}

func (v *NullableWindows11Status) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWindows11Status(val *Windows11Status) *NullableWindows11Status {
	return &NullableWindows11Status{value: val, isSet: true}
}

func (v NullableWindows11Status) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWindows11Status) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
