/*
CloudRadial

The CloudRadial API is currently in development. For more information visit <a href='https://radials.io/api' target='_blank'>https://radials.io/api</a>

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloudradial

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the FlexibleAssetBulkDeleteRequestDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FlexibleAssetBulkDeleteRequestDto{}

// FlexibleAssetBulkDeleteRequestDto struct for FlexibleAssetBulkDeleteRequestDto
type FlexibleAssetBulkDeleteRequestDto struct {
	Data []FlexibleAssetBulkDeleteDto `json:"data"`
}

type _FlexibleAssetBulkDeleteRequestDto FlexibleAssetBulkDeleteRequestDto

// NewFlexibleAssetBulkDeleteRequestDto instantiates a new FlexibleAssetBulkDeleteRequestDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFlexibleAssetBulkDeleteRequestDto(data []FlexibleAssetBulkDeleteDto) *FlexibleAssetBulkDeleteRequestDto {
	this := FlexibleAssetBulkDeleteRequestDto{}
	this.Data = data
	return &this
}

// NewFlexibleAssetBulkDeleteRequestDtoWithDefaults instantiates a new FlexibleAssetBulkDeleteRequestDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFlexibleAssetBulkDeleteRequestDtoWithDefaults() *FlexibleAssetBulkDeleteRequestDto {
	this := FlexibleAssetBulkDeleteRequestDto{}
	return &this
}

// GetData returns the Data field value
func (o *FlexibleAssetBulkDeleteRequestDto) GetData() []FlexibleAssetBulkDeleteDto {
	if o == nil {
		var ret []FlexibleAssetBulkDeleteDto
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *FlexibleAssetBulkDeleteRequestDto) GetDataOk() ([]FlexibleAssetBulkDeleteDto, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *FlexibleAssetBulkDeleteRequestDto) SetData(v []FlexibleAssetBulkDeleteDto) {
	o.Data = v
}

func (o FlexibleAssetBulkDeleteRequestDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FlexibleAssetBulkDeleteRequestDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *FlexibleAssetBulkDeleteRequestDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFlexibleAssetBulkDeleteRequestDto := _FlexibleAssetBulkDeleteRequestDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFlexibleAssetBulkDeleteRequestDto)

	if err != nil {
		return err
	}

	*o = FlexibleAssetBulkDeleteRequestDto(varFlexibleAssetBulkDeleteRequestDto)

	return err
}

type NullableFlexibleAssetBulkDeleteRequestDto struct {
	value *FlexibleAssetBulkDeleteRequestDto
	isSet bool
}

func (v NullableFlexibleAssetBulkDeleteRequestDto) Get() *FlexibleAssetBulkDeleteRequestDto {
	return v.value
}

func (v *NullableFlexibleAssetBulkDeleteRequestDto) Set(val *FlexibleAssetBulkDeleteRequestDto) {
	v.value = val
	v.isSet = true
}

func (v NullableFlexibleAssetBulkDeleteRequestDto) IsSet() bool {
	return v.isSet
}

func (v *NullableFlexibleAssetBulkDeleteRequestDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFlexibleAssetBulkDeleteRequestDto(val *FlexibleAssetBulkDeleteRequestDto) *NullableFlexibleAssetBulkDeleteRequestDto {
	return &NullableFlexibleAssetBulkDeleteRequestDto{value: val, isSet: true}
}

func (v NullableFlexibleAssetBulkDeleteRequestDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFlexibleAssetBulkDeleteRequestDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
