/*
CloudRadial

The CloudRadial API is currently in development. For more information visit <a href='https://radials.io/api' target='_blank'>https://radials.io/api</a>

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncentral

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the FlexibleAssetAttributesBulkDeleteDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FlexibleAssetAttributesBulkDeleteDto{}

// FlexibleAssetAttributesBulkDeleteDto struct for FlexibleAssetAttributesBulkDeleteDto
type FlexibleAssetAttributesBulkDeleteDto struct {
	Id int32 `json:"id"`
}

type _FlexibleAssetAttributesBulkDeleteDto FlexibleAssetAttributesBulkDeleteDto

// NewFlexibleAssetAttributesBulkDeleteDto instantiates a new FlexibleAssetAttributesBulkDeleteDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFlexibleAssetAttributesBulkDeleteDto(id int32) *FlexibleAssetAttributesBulkDeleteDto {
	this := FlexibleAssetAttributesBulkDeleteDto{}
	this.Id = id
	return &this
}

// NewFlexibleAssetAttributesBulkDeleteDtoWithDefaults instantiates a new FlexibleAssetAttributesBulkDeleteDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFlexibleAssetAttributesBulkDeleteDtoWithDefaults() *FlexibleAssetAttributesBulkDeleteDto {
	this := FlexibleAssetAttributesBulkDeleteDto{}
	return &this
}

// GetId returns the Id field value
func (o *FlexibleAssetAttributesBulkDeleteDto) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *FlexibleAssetAttributesBulkDeleteDto) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *FlexibleAssetAttributesBulkDeleteDto) SetId(v int32) {
	o.Id = v
}

func (o FlexibleAssetAttributesBulkDeleteDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FlexibleAssetAttributesBulkDeleteDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *FlexibleAssetAttributesBulkDeleteDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFlexibleAssetAttributesBulkDeleteDto := _FlexibleAssetAttributesBulkDeleteDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFlexibleAssetAttributesBulkDeleteDto)

	if err != nil {
		return err
	}

	*o = FlexibleAssetAttributesBulkDeleteDto(varFlexibleAssetAttributesBulkDeleteDto)

	return err
}

type NullableFlexibleAssetAttributesBulkDeleteDto struct {
	value *FlexibleAssetAttributesBulkDeleteDto
	isSet bool
}

func (v NullableFlexibleAssetAttributesBulkDeleteDto) Get() *FlexibleAssetAttributesBulkDeleteDto {
	return v.value
}

func (v *NullableFlexibleAssetAttributesBulkDeleteDto) Set(val *FlexibleAssetAttributesBulkDeleteDto) {
	v.value = val
	v.isSet = true
}

func (v NullableFlexibleAssetAttributesBulkDeleteDto) IsSet() bool {
	return v.isSet
}

func (v *NullableFlexibleAssetAttributesBulkDeleteDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFlexibleAssetAttributesBulkDeleteDto(val *FlexibleAssetAttributesBulkDeleteDto) *NullableFlexibleAssetAttributesBulkDeleteDto {
	return &NullableFlexibleAssetAttributesBulkDeleteDto{value: val, isSet: true}
}

func (v NullableFlexibleAssetAttributesBulkDeleteDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFlexibleAssetAttributesBulkDeleteDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
