/*
CloudRadial

The CloudRadial API is currently in development. For more information visit <a href='https://radials.io/api' target='_blank'>https://radials.io/api</a>

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloudradial

import (
	"encoding/json"
)

// checks if the Company type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Company{}

// Company struct for Company
type Company struct {
	CompanyId     *int32         `json:"companyId,omitempty"`
	Name          NullableString `json:"name,omitempty"`
	AgentFileName NullableString `json:"agentFileName,omitempty"`
	DataAgentUrl  NullableString `json:"dataAgentUrl,omitempty"`
	PsaIdentifier NullableString `json:"psaIdentifier,omitempty"`
	PsaKey        *int64         `json:"psaKey,omitempty"`
	EndpointCount *int32         `json:"endpointCount,omitempty"`
	Articles      []Article      `json:"articles,omitempty"`
	Endpoints     []Endpoint     `json:"endpoints,omitempty"`
}

// NewCompany instantiates a new Company object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCompany() *Company {
	this := Company{}
	return &this
}

// NewCompanyWithDefaults instantiates a new Company object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCompanyWithDefaults() *Company {
	this := Company{}
	return &this
}

// GetCompanyId returns the CompanyId field value if set, zero value otherwise.
func (o *Company) GetCompanyId() int32 {
	if o == nil || IsNil(o.CompanyId) {
		var ret int32
		return ret
	}
	return *o.CompanyId
}

// GetCompanyIdOk returns a tuple with the CompanyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Company) GetCompanyIdOk() (*int32, bool) {
	if o == nil || IsNil(o.CompanyId) {
		return nil, false
	}
	return o.CompanyId, true
}

// HasCompanyId returns a boolean if a field has been set.
func (o *Company) HasCompanyId() bool {
	if o != nil && !IsNil(o.CompanyId) {
		return true
	}

	return false
}

// SetCompanyId gets a reference to the given int32 and assigns it to the CompanyId field.
func (o *Company) SetCompanyId(v int32) {
	o.CompanyId = &v
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Company) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Company) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *Company) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *Company) SetName(v string) {
	o.Name.Set(&v)
}

// SetNameNil sets the value for Name to be an explicit nil
func (o *Company) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *Company) UnsetName() {
	o.Name.Unset()
}

// GetAgentFileName returns the AgentFileName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Company) GetAgentFileName() string {
	if o == nil || IsNil(o.AgentFileName.Get()) {
		var ret string
		return ret
	}
	return *o.AgentFileName.Get()
}

// GetAgentFileNameOk returns a tuple with the AgentFileName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Company) GetAgentFileNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AgentFileName.Get(), o.AgentFileName.IsSet()
}

// HasAgentFileName returns a boolean if a field has been set.
func (o *Company) HasAgentFileName() bool {
	if o != nil && o.AgentFileName.IsSet() {
		return true
	}

	return false
}

// SetAgentFileName gets a reference to the given NullableString and assigns it to the AgentFileName field.
func (o *Company) SetAgentFileName(v string) {
	o.AgentFileName.Set(&v)
}

// SetAgentFileNameNil sets the value for AgentFileName to be an explicit nil
func (o *Company) SetAgentFileNameNil() {
	o.AgentFileName.Set(nil)
}

// UnsetAgentFileName ensures that no value is present for AgentFileName, not even an explicit nil
func (o *Company) UnsetAgentFileName() {
	o.AgentFileName.Unset()
}

// GetDataAgentUrl returns the DataAgentUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Company) GetDataAgentUrl() string {
	if o == nil || IsNil(o.DataAgentUrl.Get()) {
		var ret string
		return ret
	}
	return *o.DataAgentUrl.Get()
}

// GetDataAgentUrlOk returns a tuple with the DataAgentUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Company) GetDataAgentUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DataAgentUrl.Get(), o.DataAgentUrl.IsSet()
}

// HasDataAgentUrl returns a boolean if a field has been set.
func (o *Company) HasDataAgentUrl() bool {
	if o != nil && o.DataAgentUrl.IsSet() {
		return true
	}

	return false
}

// SetDataAgentUrl gets a reference to the given NullableString and assigns it to the DataAgentUrl field.
func (o *Company) SetDataAgentUrl(v string) {
	o.DataAgentUrl.Set(&v)
}

// SetDataAgentUrlNil sets the value for DataAgentUrl to be an explicit nil
func (o *Company) SetDataAgentUrlNil() {
	o.DataAgentUrl.Set(nil)
}

// UnsetDataAgentUrl ensures that no value is present for DataAgentUrl, not even an explicit nil
func (o *Company) UnsetDataAgentUrl() {
	o.DataAgentUrl.Unset()
}

// GetPsaIdentifier returns the PsaIdentifier field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Company) GetPsaIdentifier() string {
	if o == nil || IsNil(o.PsaIdentifier.Get()) {
		var ret string
		return ret
	}
	return *o.PsaIdentifier.Get()
}

// GetPsaIdentifierOk returns a tuple with the PsaIdentifier field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Company) GetPsaIdentifierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PsaIdentifier.Get(), o.PsaIdentifier.IsSet()
}

// HasPsaIdentifier returns a boolean if a field has been set.
func (o *Company) HasPsaIdentifier() bool {
	if o != nil && o.PsaIdentifier.IsSet() {
		return true
	}

	return false
}

// SetPsaIdentifier gets a reference to the given NullableString and assigns it to the PsaIdentifier field.
func (o *Company) SetPsaIdentifier(v string) {
	o.PsaIdentifier.Set(&v)
}

// SetPsaIdentifierNil sets the value for PsaIdentifier to be an explicit nil
func (o *Company) SetPsaIdentifierNil() {
	o.PsaIdentifier.Set(nil)
}

// UnsetPsaIdentifier ensures that no value is present for PsaIdentifier, not even an explicit nil
func (o *Company) UnsetPsaIdentifier() {
	o.PsaIdentifier.Unset()
}

// GetPsaKey returns the PsaKey field value if set, zero value otherwise.
func (o *Company) GetPsaKey() int64 {
	if o == nil || IsNil(o.PsaKey) {
		var ret int64
		return ret
	}
	return *o.PsaKey
}

// GetPsaKeyOk returns a tuple with the PsaKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Company) GetPsaKeyOk() (*int64, bool) {
	if o == nil || IsNil(o.PsaKey) {
		return nil, false
	}
	return o.PsaKey, true
}

// HasPsaKey returns a boolean if a field has been set.
func (o *Company) HasPsaKey() bool {
	if o != nil && !IsNil(o.PsaKey) {
		return true
	}

	return false
}

// SetPsaKey gets a reference to the given int64 and assigns it to the PsaKey field.
func (o *Company) SetPsaKey(v int64) {
	o.PsaKey = &v
}

// GetEndpointCount returns the EndpointCount field value if set, zero value otherwise.
func (o *Company) GetEndpointCount() int32 {
	if o == nil || IsNil(o.EndpointCount) {
		var ret int32
		return ret
	}
	return *o.EndpointCount
}

// GetEndpointCountOk returns a tuple with the EndpointCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Company) GetEndpointCountOk() (*int32, bool) {
	if o == nil || IsNil(o.EndpointCount) {
		return nil, false
	}
	return o.EndpointCount, true
}

// HasEndpointCount returns a boolean if a field has been set.
func (o *Company) HasEndpointCount() bool {
	if o != nil && !IsNil(o.EndpointCount) {
		return true
	}

	return false
}

// SetEndpointCount gets a reference to the given int32 and assigns it to the EndpointCount field.
func (o *Company) SetEndpointCount(v int32) {
	o.EndpointCount = &v
}

// GetArticles returns the Articles field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Company) GetArticles() []Article {
	if o == nil {
		var ret []Article
		return ret
	}
	return o.Articles
}

// GetArticlesOk returns a tuple with the Articles field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Company) GetArticlesOk() ([]Article, bool) {
	if o == nil || IsNil(o.Articles) {
		return nil, false
	}
	return o.Articles, true
}

// HasArticles returns a boolean if a field has been set.
func (o *Company) HasArticles() bool {
	if o != nil && !IsNil(o.Articles) {
		return true
	}

	return false
}

// SetArticles gets a reference to the given []Article and assigns it to the Articles field.
func (o *Company) SetArticles(v []Article) {
	o.Articles = v
}

// GetEndpoints returns the Endpoints field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Company) GetEndpoints() []Endpoint {
	if o == nil {
		var ret []Endpoint
		return ret
	}
	return o.Endpoints
}

// GetEndpointsOk returns a tuple with the Endpoints field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Company) GetEndpointsOk() ([]Endpoint, bool) {
	if o == nil || IsNil(o.Endpoints) {
		return nil, false
	}
	return o.Endpoints, true
}

// HasEndpoints returns a boolean if a field has been set.
func (o *Company) HasEndpoints() bool {
	if o != nil && !IsNil(o.Endpoints) {
		return true
	}

	return false
}

// SetEndpoints gets a reference to the given []Endpoint and assigns it to the Endpoints field.
func (o *Company) SetEndpoints(v []Endpoint) {
	o.Endpoints = v
}

func (o Company) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Company) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CompanyId) {
		toSerialize["companyId"] = o.CompanyId
	}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.AgentFileName.IsSet() {
		toSerialize["agentFileName"] = o.AgentFileName.Get()
	}
	if o.DataAgentUrl.IsSet() {
		toSerialize["dataAgentUrl"] = o.DataAgentUrl.Get()
	}
	if o.PsaIdentifier.IsSet() {
		toSerialize["psaIdentifier"] = o.PsaIdentifier.Get()
	}
	if !IsNil(o.PsaKey) {
		toSerialize["psaKey"] = o.PsaKey
	}
	if !IsNil(o.EndpointCount) {
		toSerialize["endpointCount"] = o.EndpointCount
	}
	if o.Articles != nil {
		toSerialize["articles"] = o.Articles
	}
	if o.Endpoints != nil {
		toSerialize["endpoints"] = o.Endpoints
	}
	return toSerialize, nil
}

type NullableCompany struct {
	value *Company
	isSet bool
}

func (v NullableCompany) Get() *Company {
	return v.value
}

func (v *NullableCompany) Set(val *Company) {
	v.value = val
	v.isSet = true
}

func (v NullableCompany) IsSet() bool {
	return v.isSet
}

func (v *NullableCompany) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCompany(val *Company) *NullableCompany {
	return &NullableCompany{value: val, isSet: true}
}

func (v NullableCompany) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCompany) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
